#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "~/Dropbox/typography/memoire.org" 
#+INCLUDE: "~/Dropbox/typography/layouts.org::*Memoire" :only-contents t
#+INCLUDE: "~/Dropbox/typography/settings.org::*English" :only-contents t
#+INCLUDE: "./license.tex" export latex
#+INCLUDE: "./title_pages.tex" export latex
#+INCLUDE: "./front_matter.tex" export latex
* Introduction: Economy of the Body; Economy of the Machine
:PROPERTIES:
:PAGECOUNT: 20
:END:
** Does Labor Exist?
:PROPERTIES:
:PAGECOUNT: 10
:END:

** Society and Nature 
:PROPERTIES:
:PAGECOUNT: 10
:END:
* Did Adam Smith Invent the Computer?
:PROPERTIES:
:PAGECOUNT: 25
:END:

The introduction to this section describes the computer as a technical
object. The idea is to questoin the belief that the way to define a
computer is to think of it in terms of its components. 

A story that although was present for a long time, seems today relegated to
the confines of a few books on the history of computing. 

A document from the imprimerie Firmin Didot describes the process.

Test: this is an article from diderot encyclopedia:

# \printbibliography[heading=none,keyword=memoire,keyword=smith]

** De Prony's Tables and Human Computers
:PROPERTIES:
:PAGECOUNT: 6
:END:
This section describes de Prony' project in a holistic way. 

The documents used in this section are:

# \printbibliography[heading=none,keyword=memoire,keyword=prony,notkeyword=smith]

*** Short historical context
:PROPERTIES:
:PAGECOUNT: 3
:END:
Describe the way de Prony's project was interpreted in the context of the
French revolution. This is how is done 
*** Short technical description
:PROPERTIES:
:PAGECOUNT: 3
:END:
What was de Prony actually doing
** Can Machine Labor Replace Human Labor?
:PROPERTIES:
:PAGECOUNT: 6
:END:
This section describes the reading that Charles Babbage makes of de Prony.footcite:babbage1832

# \printbibliography[heading=none,keyword=memoire,keyword=babbage,notkeyword=smith,notkeyword=prony]

** Herbert Simon Reads Babbage
:PROPERTIES:
:PAGECOUNT: 12
:END:
This section discusses Herbert Simon's reading of Charles Babbage. If
possible, we should look for Simon's reading of de Prony's project. After
all, his article from 1958 discusses Babbage's citing of the project in his
book on European manufactures.

# \printbibliography[heading=none,keyword=memoire,keyword=simon,notkeyword=smith,notkeyword=prony,notkeyword=babbage]

* UnDemocratic Machines
:PROPERTIES:
:PAGECOUNT: 25
:END:
** Herbert Simon: Computer as Mind: Mind as Computer

Simon sought a synthesis in the form of a mathematical,
behavioral-functional, and problem centered social science that would bring
together not just choice and control but also theory and practice, research
and reform

The next step towards that synthesis was a new model of man that would
replace the homo oeconomicus of the sciences of choice and the homo
administrativus of the sciences of control. This new model of man is what
Heyck terms homo adaptivus: the bounded, rational, limited but capable,
problem-solver, with problem-solving understood as a process of adaptation
to the environment. 

In Simon's new model of man he synthesized his previous work on
administrative decision-making, contemporary cybernetics and sevomechanism
theory, and the work of Gestalt psychology of problem-solving and
productive thinking.[[footcite:heyck2005][p. 185, par. 2]] 

From



** Simon on Organizations
** Could Computers Be Democratic?
* Conclusion
:PROPERTIES:
:PAGECOUNT: 10
:END:
\lipsum

\backmatter
\chapter{Conclusion} 
\lipsum
\chapter{References} 
\printbibliography[heading=none]
