#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "~/Dropbox/typography/memoire.org" 
#+INCLUDE: "~/Dropbox/typography/layouts.org::*Memoire" :only-contents t
#+INCLUDE: "~/Dropbox/typography/settings.org::*English" :only-contents t
#+INCLUDE: "./license.tex" export latex
#+INCLUDE: "./title_pages.tex" export latex
#+INCLUDE: "./front_matter.tex" export latex
* Thoughts
I want to advance certain ideas regarding the consequences of automation on
work and employment from the perspective of historical epistemology. 

Aristotle, who had justified slavery on the seeming impossibility of
instruments operating themselves,[fn:2] would have been baffled by current
fears that artificial intelligence wipe out thousands of jobs. 


The fear of human redundancy is not new. 

 in the \ordinalnum{19} century, Sismondi was outraged at the
possibility that ``the King, alone in an island constantly turning a
handle, carry out with automatons all the work of England.''
[[cite:sismondi1819_2][p. 330, my translation]].

From a cursory view of how 


My point of view is that many of the various analysis on this matter are
marred by their narrow scope that only focuses on the possible impact of
new technologies on what economista call macroeconomic varibales. Briefly
put, the videws of neocalssical or mainstream economists, whether optimists
or pessimists are decided on whatever the economist thinkgs that the impact
of these technologies will be on macroeconomic variables such as
investment, consumption, employments, wages, etc.


* Introduction 
:PROPERTIES:
:PAGECOUNT: 7
:END:

Sunday night September 23, 1962, the /The Jetsons/, an animated sitcom, aired
for the first time, introducing audiences across the United States to the
futuristic life of the Jetson family. Just like /The Flintstones/ had done
for the Stone Age, William Hanna and Joseph Barbera celebrated the American
way of life in a future of private flying cars, nuclear family
arrangements, and---oddly enough---salary work. George Jetson, the
proverbial American /everyman/, , while his wife Jane Jetson, relieved from
the drudgery of house chores thanks to the robot maid and automated
apartment, is nonetheless relegated to the house. It is quite strange to
think that in this future, despite all the automation, neither George nor
Jane are free from work. In fact, they still have vacations in their
future, something one would think irrelevant in a time of leisure.

The problem with the Jetsons is that the horrible message it depicts: the
only change in the future is technical change but not political nor social.
The /apories/ of this conception of the possibilities of the future only in
terms of technical possibilities is, however  problematic. 
** Automation, AI and the Future of Work
That said, fears of human redundancy are not new, since already in the
\ordinalnum{19} Sismondi was preoccupied at the unemployment caused by the
greater productivity of automatic machinery, he was outraged at the
possibility that ``the King, alone in an island constantly turning a
handle, carry out with automatons all the work of England.''
[[cite:sismondi1819_2][p. 330, my translation]].

Since the last years of the \ordinalnum{20} century, advances in AI, from 
the defeat of then World Chess Champion Garry Kasparov by IBM's Deep Blue
computer in 1997 to the recent advances in self-driving cars, fears of
human redundancy in an age of more powerful and intelligent computers have
been up for over two decades, especially since the publishing of the famous
Jeremy Rifkin's book citetitle:rifkin1996. 

 
On November 14, 1957, in an address to the Twelfth National Meeting of the
Operations Research Society of America, Herbert Simon advanced the
provocative proposition that ``physicists and electrical engineers had
little to do with the invention of the digital computer'', for ``the real
inventor was the economist Adam Smith, whose idea was translated into
hardware through successive stage of development by two mathematicians,
Prony and Babbage.'' cite:simon_newell1958. 

# As you will see, this story shows that physicists and electrical engineers
#  had little to do with the invention of the digital com- puter-that the
#  real inventor was the economist Adam Smith, whose idea was translated into
#  hardware through successive stages of development by two mathematicians,
#  Prony and Babbage. (I should perhaps mention that the developers owed a
#  debt also to the French weavers and mechanics responsible for the Jacquard
#  loom, and eonsequently for the punched eard.)

** Outline of the Thesis 
This thesis is invitation to think the challenges of automation and
artificial intelligence from the point of view of the epistemology of
labor. To do so, this thesis will present a historical epistemology of the
relation between de Prony's project of the calculation of the logarithmic
tables at the /Bureau du cadastre/, Babbage's calculating Engines, and the
ideas at the time about of labor.

The first chapter discusses the relation between Adam Smith's concept of
the division of labor and Gaspard de Prony's project of the calculation of
the logarithmic tables. This story will be contextualized for it took place
at a time of great changes in French society. What will be emphasized is
that this vast computing project was, above all, the reflect of a
particular organization of /mental/ work. The idea is to provide an
understanding of the significance of the project at the time, and the
subsequent significance that it had for Charles Babbage.

The introduction to this chapter presents the reader with the story of how
Gaspard-Clair-François-Marie Riche de Prony was inspired by Adam Smith's
concept of the division of labor---as it appears in the pin factory example
of the ``Wealth of Nations''---to organize a group of hairdressers to
produce mathematical tables for the French /Bureau du cadastre/, during the
aftermath of the French Revolution. The point is to show that the
``computer'' is in fact an organization of labor, in which complex
calculation tasks are divided into simpler calculation tasks, which are
then carried out by unqualified ``specialized'' workers (or in computer
science lingo, by /sub-processes/).

In the second chapter, I will discuss the interpretation of the importance
of this project by Charles Babbage. I will show that Babbage interpreted
this project as providing a sort of proof that mental labor too could be
subject to the division of labor. The important thing to note is that
Babbage recognized the importance of this, and coupled it with the
intellectual developments at the time in the Great Britain around the
controversies of the interpretation of the algebraic developments of Boole
and De Morgan. After all, for Babbage the importance of Boole's algebra was
that it showed that thought could be reduced to symbolic operations, and
these could be mechanized through devices such as his Engines. 


# george Jetson worked three hours a day, three days a week for Mr. Spacely
# of Spacely Space Sprockets. he mostly pressed buttons. although the Jetsons
# enjoyed the standard fare of family sitcom mixups, frustrations, and
# travails, labor-saving devices of all kinds provided abundant leisure.


# googie not only brought the excitement of a jet-propelled look into 
# the everyday activities of american life, but it also colonized the new “fast” 
# medium of television. true to the age’s most popular entertainment formula— 
# the toying with both past and future—the creators of The Flintstones, hanna-
# Barbara productions, introduced The Jetsons. this animated series of 24 episodes 
# played in the prime Sunday night spot from September 1962 to March 1963. 
# after that, it became a staple of Saturday morning cartoon reruns for decades. 

# Over the years, merchandise spinoffs from The Jetsons continued to attract
# a market. the life of the Jetsons fairly bristled with googie style. their
# neighborhood boasted houses raised high above the ground on
# poles—suggesting the Cemosphere and anticipating the Seattle Space Needle.
# the family flew around the air in its private rocket-ship and traversed the
# ground in individual people movers that look just like today’s Segways.
# Sets were spare, brightly colored, modernistic. the Jetson’s googie world
# of spheres and angles and turquoise and pink projected an automated future.
# george Jetson worked three hours a day, three days a week for Mr. Spacely
# of Spacely Space Sprockets. he mostly pressed buttons. although the Jetsons
# enjoyed the standard fare of family sitcom mixups, frustrations, and
# travails, labor-saving devices of all kinds provided abundant leisure.
# Space references abounded in this future: a Moon Side Country Club, a
# space-club trip to the Moon, an auto shop called Molecular Motors. Football
# was played by robots. the family dog, astro, was acquired after a
# comparison with an electronic, nuclear-powered dog. a used robot maid,
# rosie, made a couple of appearances, but the future, after all, was fairly
# work-free.

** 取 Does Labor Exist?
* Trifling Pins & Untutored Calculators 
:PROPERTIES:
:PAGECOUNT: 10
:END:
** Introduction

# A story that although was present for a long time, seems today relegated to
# the confines of a few books on the history of computing. 

# A document from the imprimerie Firmin Didot describes the process.

A Revolutionary monument to Reason was under construction at the nearby
Bureau de Longitudes to supplement the metric system (which had been
inaugurated as nature's own measure, eternal and immutable). Although
originally commissioned as part of the Cadastre of France, launched in
1791, with Prony as director, the logarithmic tables were in fact never
used for that purpose, having been expressly designed for the decimal
division of the angles of the quadrant, which, along with the decimal
division of time was later abandoned as part of the metric system.

Calculation had not yet become mechanical, the paradigmatic example of
preocesses that were mental but not intelligent. Allied with the higher
mental faculties of speculative reason and moral judgment, calculation was
remote from the realm of menial labor, of the automatic and the habitual.

# Prony did not read their symbolism as Charles Babbage.

Astonishing feats of mental arithmetic were soon to beocme the province of
the idiot savant and the sideshow attraction, no longer the first augury of
profound mathematical gifts

Calculation took on the dull, patient associatoins of repetitive and
ill-paid bodily labor, ranked as the lowest of the mental faculties.

** Prony background
Gaspard Clair Francois Marie Riche de Prony (1755--1839) was born in
Cahmelet in the Beaujolais region of Southern France to a family of the
provincial middle bourgeoisie---the social class that would fill the ranks
of the Revolution and Empire's bureaucracy cite:picon_et_al1984. After an
education in the Classics, in 1776, when he was twenty-one, he entered the
École des ponts et chaussées in Paris.[fn:1] Prony's life coincides with a
period of the institutionalization of French sciences and techniques with
the foundation in 1794 of the École polytechnique---where he was appointed
professor of analysis and mechanics with Joseph-Louis Lagrange---and the
École normale supérieure, and a growing interest of the savants for applied
problems, and the generalization of the application of mathematical
formalisms.

# Following the educational reforms of the French Revolution, he was
# appointed professor of analysis and mechanics with Joseph-Louis Lagrange
# (1736--1813), at the newly founded Ecole Polytechnique from 1794. From 1798
# he was also made Director of the Ecole des Ponts et Chaussees, another post
# which he retained until the end of his life.
** Bureau du cadastre background  

En 1790, l’Assemblée nationale décida de remplacer les anciens impôts par
une contribution foncière assise sur le revenu net des propriétés (6). Elle
suivait en cela les idées de l’économiste François Quesnay.

Créé en 1791, le Bureau du Cadastre fut supprimé par Napoléon en 1802, qui
créa un nouveau Bureau du Cadastre en 1807, avec la mission précise de
faire établir des cadastres parcellaires dans chacune des communes
françaises (les impôts fonciers furent tou- jours en arrière-plan de ces
missions cadastrales). 

Perhaps opportunely, therefore, early on in the new decade de Prony set up
a Bureau de Cadastre in Paris, to prepare a detailed map of France to
facilitate the accurate measurement of property as a basis of taxation. In
connection with this plan, it was decided that a very large set of
logarithmic and trigonometric tables would be prepared. 

Durant onze années, le Cadastre a réalisé deux sortes de travaux : des
cartes et des tables. Nous montrerons ci-après comment ces tâches se sont
substituées à l’objectif initial qui était de nature fiscale : établir la
répartition de la contribution foncière. 

On peut distinguer cinq étapes dans les onze années d’existence du Bureau
du Cadastre. Lors de la première étape, le but du calcul de l’impôt foncier
resta primordial – on a calculé la surface des départements. Lors d’une
deuxième étape, on a calculé les grandes tables. Ce calcul s’acheva en
mars 1795. À ce moment-là, Prony répondit à une demande d’édition de tables
trigonométriques réduites, qui furent termi- nées en juillet 1795. La
quatrième étape a été celle de la détection des erreurs de calcul et de
leur correction. Les grandes tables furent calculées une deuxième fois. Les
vérifications se terminèrent au début de l’année 1798. Dans une cinquième
étape, Prony fit encore calculer quelques tables, graver diverses cartes et
dresser des exemples de cadastres communaux par type de culture.


 Prony gave some details of the project in a 'Notice' read to the classe
des sciences mathematiques et physiques in 1801, soon after it was
finished. The personnel were divided into three sections according to the
work they did. The first section contained a handful of mathematicians,
including A. M. Legendre, C. A. Prieur de la Cote d'Or, and Lazare Carnot;
the former two were also involved with the reform of weights and measures,
and latter two also acted as influential political figures. They chose the
mathematical formulae to be used for calculation and checking, and also
considered the choice of initial values of the numbers or angles, the
number of decimal places to be adopted in each table, and so on. The second
section comprised several `Calculators', including the
mathematicians A. M. Parseval (of the well-known formula in infinite
series) and the textbook writer J. G. Gamier, who determined the values,
and the differences of various orders, that needed to be calculated. They
also prepared a page of tables for the numerical work by laying out the
columns of the chosen values and the first row of entries, and preparing
the instructions on the preparation of the remaining entries on the page.
These calculations were done by the third section, a large team of between
60 and 80 assistants. Many of these workers were unemployed hairdressers;
one of the most hated symbols of the ancien regime had been the hair-styles
of the aristocracy, and the obligatory reduction of coiffure 'as the
geometers say, to its most simplest expression' left the hairdressing trade
in a severe state of recession.Thus these artists were converted into
elementary arithmeticians, executing only additions and subtractions.

When a page was completed, it was returned to the second section, to
check the figures using formulae chosen by the first section. The project
was run twice, in that two sets of each table were produced from different
equations, so that each set could be checked against the other. By 1794
seven hundred results were being produced each day.

** Technical description
What was de Prony actually doing

The pivotal moment of this transformation was Prony's project. 

Sous la Révolution, on a introduit la division centési- male du cercle en
grades : il a donc fallu calculer les tables correspondantes. Prony,
directeur du Bureau du Cadastre de 1791 à 1802, a dirigé le calcul des
logarithmes rithmes des fonctions trigonométriques de 100 000 divisions du
quart de cercle (avec quatorze décimales) et ceux des 200 000 premiers
nombres. Cette œuvre gigantesque est consignée dans seize volumes in-folio,
établis en deux exemplaires restés à l’état manuscrit.

With the adoption of the decimal-based metric system, the Revolutionary
government rendered all older trigonometric tables computed using
traditional sexagesimal divisions of the circle suddenly unusable, at least
for French geodesists and astronomers bound to the new system. 

In his capacity as director of the French cadastre, Prony was charged in
1791 to create new tables to compliment the French metric system, tables
which would awe contemporaries and posterity as ``the vastest and most
imposing monument of calculation ever executed or even conceived.''

By his own account inspired by Adam Smith's paean to the division of labor
in the first chapters of citetitle:smith1904_1, Prony organized the pyramidlike
``monument of calculation'' by means of a pyramid of tasks. 

At the apex were a handful of ``excellent mathematicians'' [ /géomètres d'un
très grand mérite/ ] who would devise the analytic formulae to be used of
the calculation; below them seven or eight ``calculators'' [ /calculateurs/;
sometimes also called /algébristes/ ] trained in analysis who would deduce
form these formulas the numbers needed to begin actual computations; and at
the base were seventy or eghty perons [ /individus/; also /ouvriers/ ] knowing
only the rudiments of arithmetic who would perform millions of additions
and subtractions and enter the values by hand into ruled folio volumes
specially laid out of the purpose. By means of these ``manufacturing''
methods, as Prony later called them, two copies of the tables, each
consisting of seventeen manuscript volumes plus instructions, were
completed by 1801.

In so doing, it pushed calculation away from intelligence and towards work. 

Eighteenth-century usage of the term intelligence overlaps but odes not
coincide with its twentieth-century meaning. Both denote mental agility,
particularly in problem solving and learning. 

For Condillac and his followers, analysis was simultaneously a method for
investigating the minds' operations and a description of those operations.
The healthy mind, unperturbed by passions or an unruly imagination, was
endlessly taking apart its ideas and sensation into their minimal elements,
then comparing and rearranging these elements into novel combinations and
permutations. 

#+ATTR_LATEX: :options [{\cite[191]{daston1994}}]
#+BEGIN_QUOTE
For Condillac, d'Alembert, Condorcet and other philosophes, thought was
a combinatorial calculus, and intelligence therefore proficient calculation
#+END_QUOTE

Force of mind, individual or collective, was at the bottom the ability to
analyze, compare, and recombine ideas, just as arithmetic was ``the art of
combining [numerical] relations.'' 

Calculation set off moral as well as intellectual resonances for
Enlightenment philosophers. Key to the moral revaluation of the interests
was the belief that they involved self-discipline as well as
self-interested calculations and therefore produced reassuringly calculable
conduct. Avarice might not be noble, but it was at least predictable and
therefore reinforced the orderliness of the social order.

#+ATTR_LATEX: :options [{\cite[192]{daston1994}}]
#+BEGIN_displayquote
Some Enlightenment writers fortified this faint praise and attempted to
recast all moral judgments, even the most laudable, as calculations.
Francis Hutcheson thought the ``Moment of Good'' produced by any given act
might be reckoned as the product of benevolence and ability; Jeremy Bentham
insisted that his sums and differences of pleasure and pain were ``nothing
but what is the practice of mankind, wheresoever they have a clear view of
their own interest.''. 
#+END_displayquote

Work and mechanical were closely linked in both French and English usage
until the middle decades of the nineteenth century, and the middle term
that joined them was the laboring body. Work taxed the body but not the
mind; even the most deft manipulations of ``rude mechanicals'' were
ascribed to habit and instinct rather than thought.

#+ATTR_LATEX: :options [{\cite[194]{daston1994}}]
#+BEGIN_displayquote
Most of those who engage in the mechanical arts have embraced them only by
necessity and work only by instinct. Hardly a dozen among a thousand can be
found who are in a position to express themselves with some clarity upon
the instrument  they use and the things they manufacture.
#+END_displayquote

Here d'Alembert repeats a commonplace: skill, the knowledge of the hand,
and habit, the enemy of reflection, had long been opposed to intelligence
and deliberation, and intimately associated with manual labor. 

#+ATTR_LATEX: :options [{\cite[55]{friedmann1953}}]
#+BEGIN_displayquote
Il est intéressant de faire ici le rapprochement des définitions que donne
l'Encyclopédie de l'« artisan » et de l'« artiste » (t. I, p. 745) : le
premier est « le nom par lequel on désigne les ouvriers qui professent ceux
d'entre les arts mécaniques qui supposent le moins d'intelligence. On dit
d'un bon Cordonnier que c'est un bon artisan, et d'un habile Horloger que
c'est un grand artiste ». Par « artiste », on entend les « ouvriers qui
excellent dans ceux d'entre les arts mécaniques qui supposent
l'intelligence ; et même à ceux qui, dans certaines Sciences, moitié
pratiques, moitié spéculatives, en entendent très bien la partie pratique ;
ainsi on dit d'un Chimiste qui fait exécuter adroitement les procédés que
d'autres ont inventés, que c'est un bon artiste ; avec cette différence que
le mot artiste est toujours un éloge dans le premier cas, et que, dans le
second, c'est presque un reproche de ne posséder que la partie subalterne
de sa profession ». — On voit que nous sommes encore fort loin des contenus
et résonances actuels. 
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[195]{daston1994}}]
#+BEGIN_displayquote
Prony himself remarked upon the social oddity represented by ``the quite
singular gathering of men who had had such different existences in the
world'' and upon the intellectual anomaly that the fewest computational
errors were made by those ``who had the most limited intelligence, an
automatic existence, so to speak''.
#+END_displayquote

Calculation had up to that point been an intellectual occupation fit for
the fines minds and the best society. 

Si la démarche de Prony demeure isolee, dans un contexte de production
encore largement traditionnel, elle marque tout de même l'ouverture d'un
novueau front. L'organisation du travail devient raient une affaire
d’ingénieur, même si le cahntier ne suit pas le mouvement, et si
l'industrialisation se fait encore attendre. 

Les tables du Cadastre prennent une connotation tout aussi politique que
scientifique. Les méthodes employees pour venir à bout de cette tâche
gigantesque traduisent qant à elles des enejxy de rationalisation sociale.
Concrètement, cette divsion du travail se manifaste par une organisation
hiérarchique des compétences. 
** Conclusion
* Mechanizing Thought
:PROPERTIES:
:PAGECOUNT: 10
:END:
** Introduction
Indeed, soon afterwards, in a pamphlet of 1822 on 'the application of
machinery to the purpose of calculating and printing mathematical
tables'---his main publication for securing governmental support for
production of the Difference Engine---he gave some account of de Prony's
project and noted that mechanical methods would speed up the process of
calculation. Clearly he was struck by de Prony's production of the tables
following an industrial process, and was hoping to imitate the process by
mechanical means. In his book on manufactures, he rehearsed some of the
same material on de Prony's project and on mechanical calculation.

Thus his contribution was to substitute manual labour by engineered
automation in the construction of tables.

This section describes the reading that Charles Babbage makes of de Prony.

The distinction between the realms of mind and matter, and the appended
distinction between the ``introspective'' and ``hypothetical'' modes of
enquiry, will prove to be of fundamental importance to understanding the
puzzled or straightforwardly dismissive reactions to Jevons' transgression
of the fields of the natural and moral sciences.

But this did not make the phenomena of the mind suited to be analyzed by
means of the same tools and methods as those of matter. Mind and matter
were considered categorically distinct phenomena. To invoke mechanical
analogies thus at no point forced the political economist to investigate
the mind with the same tools of research as nature. Indeed, Mill regarded
mechanical analogies for mental phenomena with distrust. 

Halfway through the nineteenth century, the categorical distinction between
the phenomena of mind and matter vanished under the influence of
developments within psychophysiology. This enabled economists such as
Jevons to transgress the boundaries traditionally set to the tools of the
natural sciences might be used to disclose the laws of the mind.

De Marchi (1972, 350) refers to this last mode of reasoning as ``mechanical
reasoning'', a term I consider completely apt to pinpoint Jevons's specific
contribution to the formation of modern economics. De Marchi apparently
used it to refer only to Jevons's use of mathematics in economics. 




The index of truth of these experiments was twofold. First, the
experimental results should ``mimic'' nature's complexity---but this was
only so for the informed eye that understood the causal mechanism embodied
in the experimental results. Second, the ultimate criterion of truth was a
mathematical rendering of the experimental results---that is, a
mathematical function makes the mechanism explicit of the production of the
experimental observations.

They all form instantiations of Lord kelvin's dictum (Thomson [1884] 1987,
111, also 296) that we can only understand something if we can make a
mechanical model of it. Babbage's Difference Engines and the new formal
logic developed by Boole, De Morgan, and Jevons were driving forces in the
development of mechanical reasoning in all these senses. 

** Babbage's Engines 

Babbage's calculating engines project emerged out of a growing need for
precise and accurate tables by the quickly industrializing British economy.
These tables were necessary, among other things, for navigation and for
insurance companies that were rapidly growing in importance. 

There were so many faults that could be made in the production of numerical
tables, in the computations of the ``avalanche of numbers'' comprised in
them, in the copying of the outcomes, and in the various stages of the
printing process that Herschel and Babbage spent many hours checking these
tables themselves for their own scientific purposes. One one such occasion,
as the story goes, Babbage exclaimed in exasperation that the wished these
computations had been made by ``steam'' (see for example, Swade 2000, 15).

Also, the necessity of speeding up the process of calculation was an
important factor in all of Babbage's endeavors to ``compute by steam''.
Indeed, in many ways as will be seen, the mastery of time was one of the
driving motives and major problems in Babbage's engines project. 

Good calculators, in many cases autodidacts extraordinarily gifted with
calculating capabilities, were valuable and hard to find. 

Precision, accuracy, and time were the important factors posing severe
constraints on the construction of the requested tables. It is well-known
how Gaspard de Prony's calculating project, commissioned by the French
Revolutionary regime to facilitate the conversion to the decimal system,
gave Babbage the clue in how to solve these problems jointly by the use of
machinery. Political economy provided the means to solve this seemingly
impossible task. Accidentally reading Adam Smith's /Wealth of nations/, Prony
immediately realized the importance of Smith's principle of the division of
labor and split up the work into three different task levels. In the first,
``five or six'' eminent mathematicians (including Lagrange and Prony
himself) were asked to simplify the mathematical formulae to polynomials.
In the second, a similar group of persons ``of considerable acquaintance
with mathematics'' adapted these formulae by the method of differences so
that one could calculate outcomes by simply adding  and subtracting
numbers. This final task was executed by a large number of unemployed
hairdressers. The work of this last group of computers or calculators, as
they were commonly referred to, can be rightly seen as a /reductio and
absurdum/ of manual computation (Grattan-Guinness 1992, 40; see also
Grattan-Guinness 1990c). 

 Prony's approach showed Babbage that it was possible to mechanize not only
 physical, but also mental, labor. His interest in the French project fits
 into his wider perception of algorithmic procedures in ``mathematics,
 science, and other walks of life'' (Grattan-Guinness 1992, 34). Babbage
 emphasized in /Machinery and Manufactures/ ([1835] 1963), still one of the
 most fascinating studies on the emerging mechanization of the economy,
 that the lowest task of Prony's project was ``almost'' a form of
 mechanized mental labor. Babbage designed his Difference Engine to
 mechanize this lowest stage of computing. Its method of computation
 ingeniously incorporated the method of differences in its wheels and
 gears, hence its name. Babbage's Difference Engine promised to fulfill all
 requirements Herschel and Babbage had been lamenting about: It saved
 calculation time and produced accurate and precise numbers. The
 computations would be more accurate than when done by a human
 individual---for machines, as opposed to humans, were thought not to make
 unpredictable mistakes. An attached printer would prevent errors in
 transcribing the outcomes. By thus excluding human interference from the
 whole process of computing and printing, all sources of faults---human
 faults---would be prevented, and the numbers would be precise, accurate,
 reliable, and reproducible. All this, of course, was based on the
 assumption that the machine itself operated flawlessly, a matter of great
 concern to Babbage. For all his calculating engines, he designed automatic
 checks and stops to secure its proper working.

Prony's approach affected the traditional view of the hierarchy of mental
and physical labor, Before Prony started his table project, computations
were, for the most part, made by mathematicians themselves for their own
purposes (Warwick 1995, 317--8). The routinisation and then mechanization
of computing downgraded calculation to the lowest of mental activities,
thus equating it with the routine labor executed in the emerging factories.
Babbage exploited the comparison of calculation with routine factory labor
in straightforwardly paralleling Prony's division of tasks with the
division of tasks necessary for the construction of a ``cotton or
silk-mill''. The ``multitude of other persons'' (the calculators or their
mechanical equivalent) used in their employment the ``lower degree of
skill'' (Hyman  1989, 143).

The British Government commissioned Babbage in 1823 to construct a
calculating engine. When the government stopped its funding in 1834, it had
furnished a total sum of \textsterling 17,470---an astronomical amount of
money when compared with the costs of a first-class locomotive such as the
/John Bull/, which only cost \textsterling 784 7s. 

For practical purposes, a much simpler contrivance, the so-called
arithmometer invented around 1820 by the French army officer Colmar, was of
much more use. This arithmometer, rather than Babbage's engines, became
part of the standard inventory of the first mathematics laboratory of
Whittaker in Edinburgh at the end of the century, where their careful
routinized use by scientists served the purposes Babbage dreamed of with
his calculating engines.

This museal arrangement symbolizes a perfect division of head and manual
labor, of industry and mind, in which are nonetheless embodied the very
same principles of the lever. 

With Babbage's Difference Engine, thoughts on machine intelligence were
really only speculations, for it was obvious that the calculating
capacities of the machine still involved a considerable amount of separate
mental activity that was not captured in mechanical terms. The development
of an even more ambitious machine, the Analytical Engine, seemed to
overcome these limitations. The new contrivance derived its name from its
ability to perform all ordinary analysis.

In contrast to the Difference Engine, the Analytical Engine could be really
programmed. In fact, as is well-known, the design showed great similarity
with von Neumann's computer design a century later (see Swade 2000). The
comparison Babbage made with a silk mill, in /The Economy of Machinery and
manufactures/, should be taken literally; the Analytical Engine incorporates
in its design the architecture of a factory. The Analytical Engine combined
the calculation of various functions without the interference of human mind
and hand. This was attained by the use of punched cards, an idea that
Babbage got when he was working on his book. The idea originated from the
famous Jacquard loom, in which a complex mechanism of levers regulated the
lifting of the warp in accordance with the desired pattern. This was done
by triggering the right set of levers by a role of punched cards. These
cards activated a system of levers to lift the intended column of gears.
Lovelace famously wrote that ``the Analytical Engine /weaves algebraical
patterns/, just as the jacquard-loom weaves flowers and leaves'' (Hyman
1989, 273).
** The Cogwheel Brain 
Babbage, writing of the project in 1832, was still obliged to admit that his
claim ``that the division of labor can be applied with equal success to
mental operations'' would ``appear paradoxical to some of our readers.''
The labor of mechanicals emptied the task of intelligence; yet the task at
issue, calculation, had been understood to be the very essence of
intelligence.

Babbage's reading of Prony's project as akin to setting up a silk mill was
technically correct, but the metaphorical silk mill was of the sort to be
found in late eighteenth-century Lyon, not early nineteenth-century
Manchester. Babbage's misreading of Prony's ``manufacturing'' methods
paralleled the very different meaning of /manufacturing/ in France and in
England at the time. 

Babbage understood the machines in question to be the legion of artisan
computers whose undeniable status as ``mechanicals'' served him as an
existence proof that any mental operations they could execute could also be
executed by a machine. Prony's division of labor had simply clarified which
operations those were. In contrast, Prony's machines was the entire system
of calculation, keeping with the image of the machine as a system of parts
whose hierarchical organization was governed by the principle of the
division of labor.

For Babbage, Prony's repeated appeal to ``manufacturing methods, his
emphasis upon the rapidity with which his calculators produced logarithms,
his description of their labors as ``purely mechanical operations'' all
irresistibly suggested an automated factory regimen geared to productivity
(N, pp. 6, 8n; NTL, p. 9).

#+ATTR_LATEX: :options [{\cite[198]{daston1994}}]
#+BEGIN_displayquote
Hence Babbage quite naturally undertook to replace the workers who executed
the mechanical operations with actual machines, to scale down both the
first and second sections of mathematicians and calculators in order out
save on the costs of expensive skilled labor and out conceive of these
automated, more efficient arrangements as an ongoing production of
calculations, spewing out tables at the pace and in the quantity that the
spinning jenny spun out thread.
#+END_displayquote

Jevons's approach to the moral realm only made sense once psychophysiology
and formal logic gained ground.

Originally, mechanical reasoning referred to the use of simple machines to
disclose the wonders of the universe. It had its origin in the mixed
mathematics tradition that went back to Archimedes, and that was very
important in the scientific revolution of the sixteenth and seventeenth
centuries. 

In Machamer's reading, mechanical reasoning might equally well be labeled
the Galilean approach to science. Machamer compares the role of Galileo's
simple machines to Kuhnian exemplars. An explanation of a natural
phenomenon can, by analogy, be deduced form the mechanical principles
embodied in these contrivances, and this is what Galileo consistently
attempted to attain. without any doubt, in his view, Galileo's training in
mixed mathematics played an important role in this new approach of how to
gain knowledge of nature. members of the ``mixed sciences'' (/scientia
media/) came to denote themselves as mechanical philosophers.

The use of simple contrivances like the balance as a mode of comprehending
nature---in a similar fashion as a Kuhnian exemplar---also involved
shifting criteria of proof and evidence. \ldots These ingredients for
Machamer add up to a ``clear moral'': ``To get at the true cause, you must
replicate or reproduce the effects by constructing an artificial device, so
that the effects can be seen'' (69).

In mixed mathematics, geometry was used to understand the working of simple
machines like the balance, the inclined plane, and the pendulum. 
Ironically, the Difference Engine was admired more as an edifice of reason
and engineering than for its practical usefulness. Schaffer and Swade both
relate how this little fragment showed its ``devil's tricks'' during
Babbage's popular soirees. It moved Lady Byron, the mother of Ada Lovelace,
to describe the Difference Engine as a ``thinking machine''.

Babbage was well-aware of the speculative vistas opened up by his machine.
 He never tired of telling his visitors that what seemed so miraculous and
 amazing to them had been programmed by him beforehand. Babbage was so
 content with this that the developed this idea more generally to refute
 Hume's argument against miracles. The regular--irregular output of the
 machine did not fit into Hume's idea of causation as a regular sequence of
 events---the punchline of Hume's argument---and yet this output was
 produced by the actions embodied in the mechanics of the calculating
 engine. Could it not be, so Babbage wondered, that all apparent irregular
 sequences in nature were governed by mechanical laws? God, Babbage argued
 in his unsolicited /Ninth Bridgewater Treatise/, was the programmer of
 nature, who imposed mechanical laws on it, even if we, as limited human
 beings, were not always able to decipher them.

Whewell, as seen previously, retreated from French rational mechanics
because he considered its mathematics too deductive, too much a storage
system of knowledge that was not in contact with physical reality and,
hence, not fit as an inductive instrument of enquiry. But his firm belief
in the providential order of nature was an important factor as well.
Induction could, and should, unveil the laws of nature and thus show the
providential order. This was what taxonomies---like those of Linnaeus, but
also his own geological taxonomies---produced; the ultimate cause revealed
in such taxonomies was the superior providential order in nature. 

Babbage found it ``difficult to interpret'' Whewell's thoughts on the
limits of mechanical enquiry and used his engine to give full force to the
new French mathematics of Lagrange and Laplace, as the ``theory of
invention'' he had been looking for from the days of the short-lived
Analytical Society: Mathematical analysis, in the /Bridgewater Treatise/
exemplified by Laplace, showed that miracles, probability, and free will
all could be approached as the same issue. 

Babbage's arguments against Whewell spilled over into the inner province of
the mind. What reason was there to suppose that the human mind functioned
in a different way from a calculating machine? Consciousness and freedom of
the will, to name the two great puzzles of the mind, could be mere specters
in the machinery of the mind. What the individual perceived as an act of
free will could basically be governed by the same laws that produced the
miraculous jump in a string of numbers. Equally, consciousness could be the
by-product of the invariable mechanical laws of nature. Babbage's work on
his calculating engines thus ``governed,'' as Schaffer rightly claims, his
``stories about machine intelligence'' (Schaffer 1996, 62).

Babbage went even further to argue that it would be presumptuous to
postulate any knowledge over and above what our mathematics and our
machines showed to us to argue for any non-mechanical insights. 

Babbage's severe blow to traditional categories of natural theology and
moral philosophy was only convincing, however, on the assumption that the
caprices of his calculating engines served as analogies to the world at
large, the natural and the moral, which is more or less a definition of
mechanical reasoning: to understand the world by means of machines. The
Difference Engine thus genuinely functioned as an engine of discovery. All
laws of nature, in the end, might be as mechanical as the laws governing
the engine itself. To search for these laws was to search for an algorithm
producing the plethora of concrete events. Such an algorithm is a machine.
The calculating engine and French rational mechanics proved to Babbage that
nature and mind were no more than complex computational machines. There was
no place for Whewellian ``intuition'' here.
** Conclusion
* Conclusion
:PROPERTIES:
:PAGECOUNT: 3
:END:

\lipsum

\backmatter
\chapter{Conclusion} 
\lipsum

\printbibliography

* Footnotes

[fn:2] ``For if each instrument could perform its own function on command
or by anticipating instructions, and if---like the statues of Daedalus or
the tripods of Hephaestus (which the poet describes as having ``entered the
assembly of the gods of their own accord'')---shuttles wove cloth by
themselves, and plectra played the lyre, an architectonic craftsman would
not need assistants and masters would not need slaves.'' (Politics, 15).

[fn:1] At that time, the École's tyros arrived with only the rudiments of
arithmetic and geometry. Furthermore, instead of a definite curriculum and
lectures, learning was done through self-instruction and direct practice in
construction sites cite:picon_et_al1984.
