#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "./draft_settings.org" 
# #+INCLUDE: "./license.tex" export latex
# #+INCLUDE: "./title_pages.tex" export latex
# #+INCLUDE: "./front_matter.tex" export latex
\nocite{*}
* 無 Introduction: Economy of the Body; Economy of the Machine
:PROPERTIES:
:PAGECOUNT: 15
:END:
\printbibliography[heading=none,keyword=introduction]
** Accroche: The Vagaries of the Concept of Work
:PROPERTIES:
:PAGECOUNT: 5
:END:
\printbibliography[heading=none,keyword=introduction-1]
** Problematique: Society and Nature, Rethinking Work in the 21st Century
:PROPERTIES:
:PAGECOUNT: 7
:END:
\printbibliography[heading=none,keyword=introduction-2]
** Structure of the Thesis
:PROPERTIES:
:PAGECOUNT: 2
:END:
* 無 Chapter 1
:PROPERTIES:
:PAGECOUNT: 30
:END:
** Did Adam Smith Invent the Computer?
:PROPERTIES:
:PAGECOUNT: 5
:END:
The introduction to this section describes the computer as a technical
object. The idea is to questoin the belief that the way to define a
computer is to think of it in terms of its components. 

A story that although was present for a long time, seems today relegated to
the confines of a few books on the history of computing. 

Test: this is an article from diderot encyclopedia:

A document from the imprimerie Firmin Didot describes the process.

\printbibliography[heading=none,keyword=chapter-1]
** 完 De Prony's Tables
:PROPERTIES:
:PAGECOUNT: 10
:END:
This section describes de Prony' project in a holistic way. 

The documents used in this section are:

\printbibliography[heading=none,keyword=chapter-1.1]
*** Short historical context
:PROPERTIES:
:PAGECOUNT: 3
:END:
Describe the way de Prony's project was interpreted in the context of the
French revolution. This is how is done 
*** Short technical description
:PROPERTIES:
:PAGECOUNT: 3
:END:
What was de Prony actually doing
** 完 Can Machine Labor Replace Human Labor?
:PROPERTIES:
:PAGECOUNT: 10
:END:
This section describes the reading that Charles Babbage makes of de Prony. 

\printbibliography[heading=none,keyword=chapter-1.2]
** Chapter Conclusion
:PROPERTIES:
:PAGECOUNT: 5
:END:
* 無 Chapter 2 
:PROPERTIES:
:PAGECOUNT: 25
:END:
** 無 Herbert Simon Reads Babbage
:PROPERTIES:
:PAGECOUNT: 5
:END:
This section discusses Herbert Simon's reading of Charles Babbage. If
possible, we should look for Simon's reading of de Prony's project. After
all, his article from 1958 discusses Babbage's citing of the project in his
book on European manufactures.

This section should discuss how the description of the organization of work
as a simple technical matter has undemocratic undertones. 

It could be interesting to look at what he has written on the organization
of the workplace by machines and artificial intelligence. Should we be able
to draw a parallel between his writing on organization and his views on
democracy, we are all set. 

\printbibliography[heading=none,keyword=chapter-2]
** 無 Simon on Organization
:PROPERTIES:
:PAGECOUNT: 10
:END:
\printbibliography[heading=none,keyword=chapter-2.1]
** 無 What is Industrial Democracy?
:PROPERTIES:
:PAGECOUNT: 10
:END:
Has Simon discussed the issue of democracy at the workplace besides the one
article on industrial democracy?

I want to talk about economic democracy as Alain Supiot does.  

\printbibliography[heading=none,keyword=chapter-2.2]
** Chapter Conclusion
:PROPERTIES:
:PAGECOUNT: 5
:END:
\printbibliography[heading=none,keyword=chapter-2.3]
* Conclusion
:PROPERTIES:
:PAGECOUNT: 5
:END:
\lipsum

# \backmatter
# \chapter{Conclusion} 
# \lipsum
# \chapter{References} 
# \printbibliography[heading=none]
