#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "~/Dropbox/typography/reading_list.org" 
#+INCLUDE: "~/Dropbox/typography/layouts.org::*Reading List" :only-contents t
#+INCLUDE: "~/Dropbox/typography/settings.org::*English" :only-contents t
#+INCLUDE: "./title_pages.tex" export latex
\nocite{*}
* 無 Introduction 
** 無 Accroche: A Conventionalist Epistemology
In this section, I will briefly discuss the epistemological viewpoint of
the thesis, which is that of a conventionalist epistemology. The idea is to
claim that the realist epistemology fails to understand what labor is. The
alternative is a convetionalist and historical epistemology to explain the
construction of the concept.

** 無 Metaphors in Economics
This section will introduce the topic of metaphors in economic thought,
since the main issue of the thesis is to provide historical and conceptual
elements to understand the transformations of labor in the age of
artificial intelligence and computer and information technologies (ICTs). 

This thesis takes the position that metaphors and analogies play an
important role in the way scientific concepts are understood such as in
pedagogical examples and functional analogies. 

I will state that both labor and the computer are not things but concepts,
and that their definitions must be approached historically. This chapter
will define the early computer as a conception of the organization of work
that reflects an engineering and managerial mentality. Likewise, this
chapter will hint at the link between this conception of work and its
definition in law as a relation of subordination.
** 中 Structure of the Thesis
In the last part of the introduction, I will summarize the arguments of the
three chapters and hint at the conclusion. 

# The first chapter traces the origins of the computer in de Prony and
# Babbage. The idea is to provide the reader with enough background knowledge
# to understand that the computer is not a thing but a concept, and that the
# definition of this concept has to be approached historically. This chapter
# will define the early computer as a conception of the organization of work
# that reflects an engineering and managerial mentality. Likewise, this
# chapter will hint at the link between this conception of work and its
# definition in law as a relation of subordination.

The second chapter will describe Herbert Simon's interest in Babbage, and
will speculate on how this reading shaped Simon's conception of the
computer, the relation between the natural and the artificial, the changes
in work produced by new technologies (artificial intellgence, computers,
and automation), and the organization of work in society. Moreover, this
chapter will criticize Simon's idea that the organization of work is a
purely technical problem to propose an alternative view of work that
emphases other criteria for organization such as justice, etc.

\section*{References}
\printbibliography[heading=none,keyword=introduction]
* 次 What is Labor? 
** 完  Monism: Society and Nature
In the /accroche/, I will describe how something as self-evident as labor is
in fact an ideological construct (ideological in the sense of the
anthropologist Louis Dumont, and not in the Marxist sense). Therefore, I
will briefly indicate that the concept of Labor begins in political economy
and is then appropriated by natural science to be reimported into economic
science.

Likewise, I will indicate that the motivation for the the thesis is to
rethink what Labor is in the \ordinalnum{21} century, taking into account the ubiquity
of information technologies. 
** 完 Rethinking Work in the 21st Century
In this section, I will state the main argument of the thesis: namely, that
the origin of the computer is a particular conception of the organization
of labor, which we should take into account to understand the transformation
of labor (its forms, its meaning, its formal definition in law, etc.) in the
\ordinalnum{21} century. As such, this argument calls into question the ``popular''
understanding of the one-sided transformation of labor by the appeareance
and dissemination of information and communication technologies (ICTs) in
the mid \ordinalnum{20} century. Instead, this thesis proposes to read the
computer as a technology for organizing labor, to then use this reading to
understand the transformation of labor that ICTs are supposedly pushing
for. 

** 完 Chapter Conclusion
\section*{References}
\printbibliography[heading=none,keyword=chapter-1]
* 無 The Conceptual Origins of the Computer
The first chapter introduces the definition of the early computer as a
technology for organizing work. The first objective of this chapter is to
question the belief that the appropriate definition of the computer is in
terms of its components. The second objective is to acquaint the reader
with the history of the early computer by describing the project of the
calculation of the logarithmic tables at the /Bureau du cadastre/, and the
importance that this project had for Charles Babbage's calculating
machines.
** 完 Did Adam Smith Invent the Computer?
This chapter will open with Simon and Newell's text,
citetitle:simon_newell1958, in which they discuss de Prony's project and it
is influence on Charles Babbage.

The introduction to this chapter presents the reader with the story of how
Gaspard-Clair-François-Marie Riche de Prony was inspired by Adam Smith's
concept of the division of labor---as it appears in the pin factory example
of the ``Wealth of Nations''---to organize a group of hairdressers to
produce mathematical tables for the French /Bureau du cadastre/, during the
aftermath of the French Revolution. The point is to show that the
``computer'' is in fact an organization of labor, in which complex
calculation tasks are divided into simpler calculation tasks, which are
then carried out by unqualified ``specialized'' workers (or in computer
science lingo, by /sub-processes/).

The first section of this chapter contextualizes the story of De Prony, by
providing some background information on him and on the project of the
calculation of the logarithmic tables. The idea is to provide an
understanding of the significance of the project at the time, and the
subsequent significance that it had for Charles Babbage.

** 完 Babbage's Thinking Machines

The second chapter will discuss the question at the heart of Babbage's
project: Can machine labor replace human labor?

The second section of this chapter connects De Prony's story with Babbage's
design of the Difference and the Analytical Engine. The idea is to connect
Babbage's ideas on the organization of work and industry with his thought
on calculating devices. Therefore, the concept of /mental labor/ will be
discussed, as it relates to the \ordinalnum{20} century analogy between
mind and computer---which is key to the thought of Herbert Simon.   

** 完 Chapter Conclusion
\section*{References}
\printbibliography[heading=none,keyword=chapter-2]
* 無 The Bureaucracy as Model Computer
The second chapter describes Herbert Simon's thinking on the computer and
organizations to trace the consequences of these ideas into his thinking
about the role of artificial systems in shaping the workplace and worker
self-determination. Therefore, this chapter will introduce the reader to
the importance of Herbert Simon to the field of artificial intelligence,
which has been more-or-less ignored by economists---who often only focus on
his concept of /bounded rationality/.
** 無 The Mind and the Computer
The introduction of this chapter discusses the ambiguous relation between
nature and artifice in the thought of Herbert Simon---specially, as it
manifests in his understanding of the mind as a computer. The idea is to
give the reader enough background information on Simon's general vision of
/things/ to, then, discuss his thinking on the nature of organizations (in
the first section).

** 無 Dichotomy: Natural and Artificial
The first section of this chapter connects Simon's ideas on the computer
and the mind to his general thinking on organizations. The idea is to pave
the way for a political understanding of Simon's more abstract writings on
organizations by presenting Simon's own thinking on the concrete social
consequences of his vision---which is done in the second section.

** 取 Could Computers Be Democratic?
The second section of this chapter connects Simon's general ideas on
organizations to his thought on the role of artificial systems (machines,
automation, ICTs, artificial intelligence, etc.) in shaping the workplace.
Moreover, this section will discuss his problematic concept of a ``science
of the artificial'' as it relates to the organization of labor---after all,
there's nothing more artificial than the institution of wage earning. The
idea is to show that the description of the organization of labor as a
purely technical matter has terrible consequences for worker
self-determination, and that this understanding of the worker as a just a
cog in the production process is not questioned by Simon, and thus,
unlikely to change under the new information technologies.

** 完 Chapter Conclusion
\section*{References}
\printbibliography[heading=none,keyword=chapter-3]
* Conclusion

# This thesis only hints at the importance of the concept of information in
# the \ordinalnum{20} century science. A more thorough understainding of this
# is necessary to understand the conceptual changes in \ordinalnum{20}
# century economics. 

# \lipsum

# \backmatter
# \chapter{Conclusion} 
# \lipsum
# \chapter{References} 
# \printbibliography[heading=none]
