#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "./settings.org" 
#+INCLUDE: "./license.tex" export latex
#+INCLUDE: "./title_pages.tex" export latex
#+INCLUDE: "./front_matter.tex" export latex
* Introduction: Economy of the Body; Economy of the Machine
:PROPERTIES:
:PAGECOUNT: 20
:END:
** Does Labor Exist?
:PROPERTIES:
:PAGECOUNT: 10
:END:

** Society and Nature 
:PROPERTIES:
:PAGECOUNT: 10
:END:
* Did Adam Smith Invent the Computer?
:PROPERTIES:
:PAGECOUNT: 25
:END:

The introduction to this section describes the computer as a technical
object. The idea is to questoin the belief that the way to define a
computer is to think of it in terms of its components. 

A story that although was present for a long time, seems today relegated to
the confines of a few books on the history of computing. 

A document from the imprimerie Firmin Didot describes the process.

Test: this is an article from diderot encyclopedia:

# \printbibliography[heading=none,keyword=memoire,keyword=smith]

** De Prony's Tables
:PROPERTIES:
:PAGECOUNT: 6
:END:
This section describes de Prony' project in a holistic way. 

The documents used in this section are:

# \printbibliography[heading=none,keyword=memoire,keyword=prony,notkeyword=smith]

*** Short historical context
:PROPERTIES:
:PAGECOUNT: 3
:END:
Describe the way de Prony's project was interpreted in the context of the
French revolution. This is how is done 
*** Short technical description
:PROPERTIES:
:PAGECOUNT: 3
:END:
What was de Prony actually doing
** Can Machine Labor Replace Human Labor?
:PROPERTIES:
:PAGECOUNT: 6
:END:
This section describes the reading that Charles Babbage makes of de Prony.footcite:babbage1832

# \printbibliography[heading=none,keyword=memoire,keyword=babbage,notkeyword=smith,notkeyword=prony]

** Herbert Simon Reads Babbage
:PROPERTIES:
:PAGECOUNT: 12
:END:
This section discusses Herbert Simon's reading of Charles Babbage. If
possible, we should look for Simon's reading of de Prony's project. After
all, his article from 1958 discusses Babbage's citing of the project in his
book on European manufactures.

# \printbibliography[heading=none,keyword=memoire,keyword=simon,notkeyword=smith,notkeyword=prony,notkeyword=babbage]

* UnDemocratic Machines
:PROPERTIES:
:PAGECOUNT: 25
:END:

This section should discuss how the description of the organization of work
as a simple technical matter has undemocratic undertones. 

Has Simon discussed the issue of democracy at the workplace besides the one
article on industrial democracy?

It could be interesting to look at what he has written on the organization
of the workplace by machines and artificial intelligence. Should we be able
to draw a parallel between his writing on organization and his views on
democracy, we are all set. 
** What is Industrial Democracy?
I want to talk about economic democracy as Alain Supiot does.  


\lipsum
** 取 Administrative Behavior
\lipsum
** 取 Artificial Intelligence
* Conclusion
:PROPERTIES:
:PAGECOUNT: 10
:END:
\lipsum

\backmatter
\chapter{Conclusion} 
\lipsum
\chapter{References} 
\printbibliography[heading=none]
