#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "./notes_settings.org" 
#+INCLUDE: "./license.tex" export latex
#+INCLUDE: "./notes_title_pages.tex" export latex
* 取 \ordinalnum{1} Week 
** 17/09/2018 
** 18/09/2018 
** 19/09/2018 
** 20/09/2018 
** 21/09/2018 
** 22/09/2018 
** 23/09/2018 
* 取 \ordinalnum{2} Week 
** 24/09/2018 
** 25/09/2018 
** 26/09/2018 
** 27/09/2018 
** 28/09/2018 
** 29/09/2018 
** 30/09/2018 
* 取 \ordinalnum{3} Week 
** 01/10/2018 
** 02/10/2018 
** 03/10/2018 
** 04/10/2018 
** 05/10/2018 
** 06/10/2018 
** 07/10/2018 
* 取 \ordinalnum{4} Week 
** 08/10/2018 
** 09/10/2018 
** 10/10/2018 
** 11/10/2018 
** 12/10/2018 
** 13/10/2018 
** 14/10/2018 
* 取 \ordinalnum{5} Week 
** 15/10/2018 
** 16/10/2018 
** 17/10/2018 
** 18/10/2018 
** 19/10/2018 
** 20/10/2018 
** 21/10/2018 
* 取 \ordinalnum{6} Week 
** 22/10/2018 
** 23/10/2018 
** 24/10/2018 
** 25/10/2018 
** 26/10/2018 
** 27/10/2018  
** 28/10/2018 
* 取 \ordinalnum{7} Week - Toussaint 
** 29/10/2018 
** 30/10/2018 
** 31/10/2018 
** 01/11/2018 
** 02/11/2018 
** 03/11/2018 
** 04/11/2018 
* 取 \ordinalnum{8} Week 
** 05/11/2018 
** 06/11/2018 
** 07/11/2018 
** 08/11/2018 
** 09/11/2018 
** 10/11/2018 
** 11/11/2018 
* 取 \ordinalnum{9} Week 
** 12/11/2018 
** 13/11/2018 
** 14/11/2018 
** 15/11/2018 
** 16/11/2018 
** 17/11/2018 
** 18/11/2018 
* 取 \ordinalnum{10} Week 
** 19/11/2018 
** 20/11/2018 
** 21/11/2018 
** 22/11/2018 
** 23/11/2018 
** 24/11/2018 
** 25/11/2018 
* 取 \ordinalnum{11} Week 
** 26/11/2018 
** 27/11/2018 
** 28/11/2018 
** 29/11/2018 
** 30/11/2018 
** 01/12/2018 
** 02/12/2018 
* 取 \ordinalnum{12} Week 
** 03/12/2018 
** 04/12/2018 
** 05/12/2018 
** 06/12/2018 
** 07/12/2018 
** 08/12/2018 
** 09/12/2018 
* 取 \ordinalnum{13} Week 
** 10/12/2018 
** 11/12/2018 
** 12/12/2018 
** 13/12/2018 
** 14/12/2018 
** 15/12/2018 
** 16/12/2018 
* 取 \ordinalnum{14} Week 
** 17/12/2018 
** 18/12/2018 
** 19/12/2018 
** 20/12/2018 
** 21/12/2018 
** 22/12/2018 
** 23/12/2018 
* 取 \ordinalnum{15} Week - Noël                                                                  :noexport:
** 24/12/2018 
** 25/12/2018 
** 26/12/2018 
** 27/12/2018 
** 28/12/2018 
** 29/12/2018 
** 30/12/2018 
* 完 \ordinalnum{16} Week - Noël 
** 取 31/12/2018                                                                                  
** 01/01/2019 
 I am thinking about how to structure the thesis to limit the reading list
 to a manageable expression.  

I might have a somewhat clear idea of what to put in the first chapter:
background on the Cold War and the computer, Simon's place in the context
of the creation of the computer, and Simon's history between the computer
and artificial intelligence. This part could benefit from relating the
computer to artificial intelligence. After all, Simon did write about the
computer in his writings, but as far as I am aware, he spoke more about
artificial intelligence than about computers per se. 

Perhaps, in that sense, it would be worth it to look at all of Simon's
explicit writings on the computer \ldots it seems I would need to read, on
top of «Administrative Behavior», his «The Sciences of the Artificial». I
would like to limit the amount of books to read for the thesis, but it
seems unavoidable to read one book on the history of the computer. Should I
fall short of time, it should be Edward's «The Closed World».

As in my previous discussion with Prof. Lenfant, we agreed that
introducing the topic of artificial intelligence is more difficult than it
appeared at first sight, we might be forced to talk more about the
organization of labor rather than artificial intelligence. In fact thinking
about it, we should, perhaps, forget about artificial intelligence at this
point, and talk about the computer as a social technology. 

I am beginning to sense that the biggest challenge at this point really is
choosing the corpus. The problem is that if the topic is to broad as to
require a vast amount of reading to treat satisfactorily, the thesis will
be ambitious but an utter failure. The topic must be adjusted to reduce the
reading to an amount that is manageable within the time constraints and
that allows a satisfactory treatment of the subject. 

Today, I am checking Simon's «Models of Bounded Rationality, Vol 3.», which
was published in 1997, just a few years before his death. Vol. 1 dates
from 1982. Vol. 2 from 1982 (1984 the softcover edition). It is very likely
that the motivation for this collection comes from his receiving the Nobel
Prize in Economics in 1978. In other words, there is a 15 year gap between
the first volumes and the third. It would be interesting to find out the
history behind the motivation for the publication of the third volume, but
this would be impossible to undertake at this point. 

The following is the description of Vol. 2 from the MIT Press website:

#+BEGIN_QUOTE
The Nobel Prize in Economics was awarded to Herbert Simon in 1978. At
Carnegie-Mellon University he holds the title of Professor of Computer
Science and Psychology. These two facts together delineate the range and
uniqueness of his contributions in creating meaningful interactions among
fields that developed in isolation but that are all concerned with human
decision-making and problem-solving processes. In particular, Simon has
brought the insights of decision theory, organization theory (especially as
it applies to the business firm), behavior modeling, cognitive psychology,
and the study of artificial intelligence to bear on economic questions.
This has led not only to new conceptual dimensions for theoretical
constructions, but also to a new humanizing realism in economics, a way of
taking into account and dealing with human behavior and interactions that
lie at the root of all economic activity.

The sixty papers and essays contained in these two volumes are grouped
under eight sections, each with a brief introductory essay. These are: Some
Questions of Public Policy, Dynamic Programming Under Uncertainty;
Technological Change; The Structure of Economic Systems; The Business Firm
as an Organization; The Economics of Information Processing; Economics and
Psychology; and Substantive and Procedural Reality.

Most of Simon's papers on classical and neoclassical economic theory are
contained in volume one. The second volume collects his papers on
behavioral theory, with some overlap between the two volumes. The second
edition of Simon's widely read and referenced The Sciences of the
Artificial was published by The MIT Press 1981 and is available in both
hardcover and paperback.
#+END_QUOTE

From the preface to Vol. 3, it seems to me that Simon had a big say on what
papers were chosen for these volumes. He claims that the papers contained
therein have historical interest. They constitute, to his judgment, the
principal papers in economics. Thus, as we can infer from the introduction
to the third volume, since these papers do not get into his published
books, taking those aside, these papers constitute the /principal/ papers
Simon wrote dealing with economics according to his personal appreciation.

Simon claims that the reason the categories used in Vol. 3 doesn't match
those of the previous volumes is that his interests changed dramatically.
Apparently, vol. 3 includes mostly papers from the 1980s and 1990s, such as
formal representation of causal ordering (closely connected with the
identification problem) in dynamic systems., the implications for our
society of the new information systems that are being generated as products
of the rapid deveoplment of computers and electronic communication
networks, and the nature of employee and managerial motivation in the
bvusiness firm, and the implications for economics of the propensity of
human beings to identify with the goals of organizations, and the state of
economics itself (its changing attituted toward formal theory vis-à-vis
empirical research). It is interesting that the topic of the apllication of
economics to governmental administration and policy, and rational choice
under uncertainty and technological change are hardly represented in this
volume. 

Use the following guide when comparing the changes in Simon's thought
between the two volumes:

#+ATTR_LATEX: :booktabs :environment tabularx :width \columnwidth :align XX
| *Volume 3*                                      | *Volumes 1 and 2*                         |
|-----------------------------------------------+-----------------------------------------|
| Simulating Large Systems                      | Structure of Economic Systems           |
|-----------------------------------------------+-----------------------------------------|
| The Advance of Information Technology         | The Economies of Information Processing |
|-----------------------------------------------+-----------------------------------------|
| Motivation and the Theory of the Firm         | The Business Firm as an Organization    |
|-----------------------------------------------+-----------------------------------------|
| Behavrioral Economics and Bounded Rationality | Economics and Psychology                |
|                                               | Substantive and Procedural Rationality  |
|-----------------------------------------------+-----------------------------------------|
| The Structure of Complex Systems              | Causes and Possible Worlds              |

In any case, for now I think we better just finish up the three papers we
had begun reading: the one by Hunter Heyck, the two by Simon. Then, we can
discuss what to read next, although the papers in Vol. 3 dealing with the
impact of communications technologies seem to be next. Likewise, reading
«Administrative Behavior» seems to be a must. For now, let's stay clear of
books on the computer, for they may not be relevant to Simon's own
thinking: I must find out who were Simon's intellectual forefathers in
terms of thinking about computing. 

#+BEGIN_QUOTE
What I've uncovered in a lot of my work is that nature is used to define
the economy, and the economy is then used to define nature. It's just this
incredible round robin.

\ldots constantly, they are taking these models over and defining the
market to operate like a physical process.

The dominant images of nature have never been very far removed from
dominant images of economic activity. Indeed, many of the same formalism
and ontological commitments tend to cover both, although, the periods of
orthodoxy in the respective fields may move out of phase. Therefore, on the
long horizon of Western thought, nature is not something external that hems
the economy in. Rather, they constitute and mimic one another. For in the
West, it is as hard to sustain the pretense that economy and nature are
pitted in remorseless conflict as it is to acknowledge that Jesus was not a
Caucasian or that money never buys happiness. Philosophers such as Derrida
have made us more aware of the unstable antinomies or, as he dubbed them,
the ghost of the undecidable.

\RaggedLeft Philip Mirowski, \linebreak Lecture presented by the UTS
Cosmopolitan Civil Socities Research Centre and the Australian Working
Group on Financialisation at the University of Sydney (24-\ordinalnum{25}
July 2012). 
#+END_QUOTE
** 取 02/01/2019 
** 取 03/01/2019 
** 取 04/01/2019 
** 05/01/2019 
The corpus must not be delimited arbitrarily. Instead, the research
question must be thinkered with to reflect upon a corpus. In other words,
the research question will be the one to determine the corpus. I must
change the research question for it to define an appropriate corpus that
fits the time constraints of the Master's. 

I believe that some way of combining history of ideas (Rabinbach),
sociology of science (Vatin, Meda, Castel), and the work of Herbert Simon
would be nice for a PhD thesis but not for a Master's thesis. For now, we
should reduce our ambitions and \ldots
** 取 06/01/2019 
* 完 \ordinalnum{17} Week 
** 取 07/01/2019 
** 取 08/01/2019 
** 取 09/01/2019 
** 10/01/2019 
Taking into accoun the little time left for research, I have decided to
stick to Mendeley for managing pdfs, and instead use a custom bibliography
file to use BibLaTeX's 'origdate' field. As of today, none of BibLaTeX's
default styles use this field, which necessitates redefining a macro, for
it to print at all. Unfortunately, this is the only /reasonable/ modification
available for having this information displayed. Although a LaTeX package,
~chicago-bilatex~ exists, the documentation is extensive (over 150 pages),
which is more than I can afford to read at this moment on 'carpentry'.
After the Master's thesis is completed, time could be devoted to stuyding
this package in detail, but not for now. 

The other problem is that Mendeley does not implement the 'origdate' field
in its templates, which forces me out of it. Should Mendeley implement this
field in future releases, there would be no reason to change, since, as of
today, I haven't come across a better alternative to manage pdfs. Although
people have suggested Zotero, its meager BiBLaTeX support completely
defeats the purpose of using it. Although using Mendeley's collections is
perhaps of little use, since Emacs Org mode is better at organizing those
for research (briefly, Mendely is too slow), keeping files organized in
forlders by 'author', named with the format 'name-year-title', is something
Mendeley excells at. Although using a combination of free software tools
could accomplish the same thing, I prefer having all that in one neat
package that includes pdf highlighting, pdf search, etc. Until a better
alternative arises, Mendeley stays, if only for its powerful organizing
tools.
** 取 11/01/2019 
** 取 12/01/2019 
** 取 13/01/2019 
* 中 \ordinalnum{18} Week 
** 取 14/01/2019 
** 取 15/01/2019 
** 16/01/2019 
I feel that centering the thesis around Herbert Simon sort of forces the
argument in unnatural ways. The past few days, I have almost finished
creating the snippets to speed up collecting bibliographic data. It seems
to me that it is not very efficient to collect absolutely everything in
BibTeX format: Even with current technology, it still takes too much time
to classify everything. 

The strategy for the meantime is as follows: To prevent spending too much
time reading primary sources with only a tenous connection to the argument,
we have to identify a /feiulle de route/ to guide our approach to the primary
sources. That is, to avoid spending weeks perusing archival material, we
let a connoisseur of the archive guide us to the relevant primary sources.
We consult the primary sources, we extract what we need, and only then,
should something be missing, we go back to the archives. Otherwise, one
risks trying to reinvent the computer a second time. The whole point of
scholarly research is to build upon the shoulders of giants. In this point,
I disagree profoundly with the advice of two professors against approaching
primary sources from secondary sources: They are wrong in thinking that
doing so /colors/ one's perspective on the primary sources to the point where
developing an original reading is made more difficult. It is necessary to
consult the secondary sources /first/, in order to check whether one's
hunches   about a particular point of view have been explored in the
literature already. Only by knowing /that,/ can one have an original point of
view. Otherwise, the risk is too high of ignoring an important primary
source that has been already studied. Briefly, attack secondary sources
first; then, go for primary sources! 

​Regarding the actual thesis work, I had originally planned several planning
stages before undertaking actual writing, but this approach seems laughably
unpractical. Rather, I already finished the actual Emacs org mode file to
use for writing the thesis. The typesetting and the title pages are all
complete. Now, we can focus for the most part in writing \ldots more or
less. There are a few BibLaTeX macros I haven't coded, but I will code them
as I go. 

Regarding the subject matter, I am reorienting the whole edifice towards
the reading that Simon makes of Babbage, and the reading Babbage makes of
Prony. I am thinking about the difference between several levels: What the
actions and texts of these authors represented for the people at the time,
that is to say, how people living at the time, including the author
himself, interpreted the significance of their actions (works, texts,
etc.). The other level is how other people \ldots one could call them
commentators, have interpreted these actions later on, because it is
usually the views of famous commentators that becomes the standard way of
interpreting (one could even say /reading/) the event. Thus, in order to
evaluate an event, we must be aware of these three dimensions: how the
authors interpreted his own actions, how the people at the time of the
author interpreted them, and how the commentators have successively
interpreted the event. This questioning will in fact open the way for our
own interpretation. 

Regarding, M. Prony, his contribution is well known, and it is still known
in circles dedicated to the history of computing and the history of
mathematics. So, in the first part, I could, in fact, list the different
readings of de Prony's project, to try to differentiate how it has been
interpreted by Prony himself, by living people at the time, by Babbage, and
by other scholars. Of course, the idea is to focus on the interpretation
that Babbage makes of the significance of the project. And then, we can use
this, to discuss the interpretation that Simon makes of Babbage. In other
words, we could just discuss the texts where Simon discusses Babbage's
project to glance at what his interpretation was. But, we must be careful
to avoid focusing too much on issues on interpretation because the whole
point of the thesis is not to simply discuss interpretations of this one
event in post-revolutionary France; the whole point is to discuss these
interpretations in the context of thought on work and the organization of
work. 

Essentially, my goal with the thesis is to open the way to rethink the
place, the importance, and the conceptualization of work within economics,
all in the context of the transformation of labor in the 21st century,
which will be shaped by ICTs. What I want to discuss is that ICTs transform
labor not just because they suddenly appeared, and there's lots of them
today. I want to claim that they have been shaped by particular conceptions
of what labor is, and they in turn now shape what labor will be. But, the
point is not to encourage a technological determinism /a la/ Marshall
McLuhan. The idea is to claim that technical objects can embody certain
conceptions, but changing conceptions can also transform technological
objects. 

In the case of the computer, what would it be like to interact with the
computer, as if it was a conversation? What would it be like to interact
with a computer democratically? 

On a different note, this is some idea I drafted while on the \textsc{rer} today: 

#+BEGIN_QUOTE
How Can the history of the computer clarify the transformation of labor in
the 21st century? Can this history help us understand the way the
relationship between artificial intelligence and the changes it portends
over work? Could an understanding of this history clarify the way to
question the definition of what work should be and the way it shoube
evaluated in the 21st century?

With this thesis I would like to \ldots 

In the first part of the thesis, I will discuss and retell the history of
the origins of the computer in political economy and the engineering
mentality. 

In the second part of the thesis, I will discuss the \ldots 
#+END_QUOTE
** 17/01/2019 
** 18/01/2019 
** 19/01/2019 
** 20/01/2019 
* 無 \ordinalnum{19} Week 
** 21/01/2019 
** 22/01/2019 
** 23/01/2019 
** 24/01/2019 
** 25/01/2019 
** 26/01/2019 
** 27/01/2019 
* \ordinalnum{20} Week 
** 28/01/2019 
** 29/01/2019 
** 30/01/2019 
** 31/01/2019 
** 01/02/2019 
** 02/02/2019 
** 03/02/2019 
* \ordinalnum{21} Week 
** 04/02/2019 
** 05/02/2019 
** 06/02/2019 
** 07/02/2019 
** 08/02/2019 
** 09/02/2019 
** 10/02/2019 
* \ordinalnum{22} Week 
** 11/02/2019 
** 12/02/2019 
** 13/02/2019 
** 14/02/2019 
** 15/02/2019 
** 16/02/2019 
** 17/02/2019 
* \ordinalnum{23} Week 
** 18/02/2019 
** 19/02/2019 
** 20/02/2019 
** 21/02/2019 
** 22/02/2019 
** 23/02/2019 
** 24/02/2019 
* \ordinalnum{24} Week 
** 25/02/2019 
** 26/02/2019 
** 27/02/2019 
** 28/02/2019 
** 01/03/2019 
** 02/03/2019 
** 03/03/2019 
* \ordinalnum{25} Week - Hiver
** 04/03/2019 
** 05/03/2019 
** 06/03/2019 
** 07/03/2019 
** 08/03/2019 
** 09/03/2019 
** 10/03/2019 
* \ordinalnum{26} Week 
** 11/03/2019 
** 12/03/2019 
** 13/03/2019 
** 14/03/2019 
** 15/03/2019 
** 16/03/2019 
** 17/03/2019 
* \ordinalnum{27} Week 
** 18/03/2019 
** 19/03/2019 
** 20/03/2019 
** 21/03/2019 
** 22/03/2019 
** 23/03/2019 
** 24/03/2019 
* \ordinalnum{28} Week 
** 25/03/2019 
** 26/03/2019 
** 27/03/2019 
** 28/03/2019 
** 29/03/2019 
** 30/03/2019 
** 31/03/2019 
* \ordinalnum{29} Week 
** 01/04/2019 
** 02/04/2019 
** 03/04/2019 
** 04/04/2019 
** 05/04/2019 
** 06/04/2019 
** 07/04/2019 
* \ordinalnum{30} Week 
** 08/04/2019 
** 09/04/2019 
** 10/04/2019 
** 11/04/2019 
** 12/04/2019 
** 13/04/2019 
** 14/04/2019 
* \ordinalnum{31} Week 
** 15/04/2019 
** 16/04/2019 
** 17/04/2019 
** 18/04/2019 
** 19/04/2019 
** 20/04/2019 
** 21/04/2019 
* \ordinalnum{32} Week 
** 22/04/2019 
** 23/04/2019 
** 24/04/2019 
** 25/04/2019 
** 26/04/2019 
** 27/04/2019 
** 28/04/2019 
* \ordinalnum{33} Week 
** 29/04/2019 
** 30/04/2019 
** 01/05/2019 
** 02/05/2019 
** 03/05/2019 
** 04/05/2019 
** 05/05/2019 
* \ordinalnum{34} Week 
** 06/05/2019 
** 07/05/2019 
** 08/05/2019 
** 09/05/2019 
** 10/05/2019 
** 11/05/2019 
** 12/05/2019 
* \ordinalnum{35} Week 
** 12/05/2019 
** 13/05/2019 
** 14/05/2019 
** 15/05/2019 
** 16/05/2019 
** 17/05/2019 
** 18/05/2019 
** 19/05/2019 
