#+STARTUP: indent nostars logdrawer showeverything
#+SETUPFILE: "~/Dropbox/typography/memoire.org" 
#+INCLUDE: "~/Dropbox/typography/layouts.org::*Memoire" :only-contents t
#+INCLUDE: "~/Dropbox/typography/settings.org::*English" :only-contents t
#+INCLUDE: "./license.tex" export latex
#+INCLUDE: "./title_pages.tex" export latex
#+INCLUDE: "./front_matter.tex" export latex
* Notes & Tasks                                                                                    :noexport:
The organization of part one of chapter one is not very clear.  I must work
it out to reflect Autor's position accurately, so the best thing to do
would be to just mention certain points in his argument that are related to
the counterpoints I will mobilize in the following section. 


The summary for the technicist view is done. 

Part two of chapter one, the criticism of the technicist view, has some
good ideas, but they are kinda scattered and not presented systematically.




* 待 Introduction 
#+ATTR_LATEX: :options [:]{} 
#+BEGIN_labeling
\item[TS] The dominant "technicist" view of the influence of ICTs on the
future of work and its organization is inadequate because it ignores that
thoughts on machine intelligence, automation, and sociotechnical systems
for the conduct of workers have been strongly connected since at least the
nineteenth century.
#+END_labeling


That said, fears of human redundancy are not new, since already in the
\ordinalnum{19} Sismondi was preoccupied at the unemployment caused by the
greater productivity of automatic machinery, he was outraged at the
possibility that ``the King, alone in an island constantly turning a
handle, carry out with automatons all the work of England.''
[[cite:sismondi1819_2][p. 330, my translation]].


# As the recurring interest in de Prony's project for the calculation of
# the logarithmic tables shows, the dominant "technicist" view of the
# influence of ICTs on the future of work and its organization is
# inadequate because it ignores that thoughts on machine intelligence,
# automation, and sociotechnical systems for the conduct of workers have
# been strongly connected since at least the nineteenth century.


# To show this, I will analyze a paper by David Autor, a reputed mainstream
# economist who has treated the questions of the influence of artificial
# intelligence and automatoin on jobs and the economy, and then I will

# The core of Schaffer's argument is that the factory system wasn't simply a
# technological change but a technology of discipline and surveillance. He
# shows that this implication of discipline and surveillance of the factory
# system wasn't an unintended consequence---those dear to latter-day
# advocates of the /Harmonies economiques/---of technical changes. On the
# contrary, the philosophy of the machine was from the very beginning an
# embodiment of an organization of labor: a way to discipline the laboring
# body. 
** 無 Structure of the thesis 
As the recurring interest in de Prony's project for the calculation of the
logarithmic tables shows, the dominant "technicist" view of the influence
of ICTs on the future of work and its organization is inadequate because it
ignores that thoughts on machine intelligence, automation, and
sociotechnical systems for the conduct of workers have been strongly
connected since at least the nineteenth century.

In chapter one, I (1) explain what the dominant "technicist" view is, and
(2) criticize it the best I can to show that it is inadequate. The first
part of chapter one explains what the technicist view is, and uses the
example of Autor's article as an ideal-type of this view. The second part
of chapter one criticizes the technicist view by showing that it ignores
the conventionalist dimension of the wage relation. This is done by
discussing the social embeddedness of work in history, culture, and western
ideology and discussing the example of the work contract by Supiot. 

# The dominant technicist view, which analyses the perils of ICTs for the
# future of work in terms of the possibilities to automate different
# (categories of) tasks, is inadequate because it ignores the conventionalist
# dimension of the wage relation by construing work from a realist
# epistemology.

In chapter two, I should sketch a different view (to the dominant
technicist one) by explaining how the recurring interest in de Prony's
project shows that thoughts on machine intelligence, automation, and
sociotechnical systems for the conduct of workers have been connected since
at least the nineteenth century. The first part of chapter two shows that
the origins of the computer lie in a technical organization of labor that
is related to the factory system and the concept of the division of
(mental) labor. The second part of chapter two shows that this fact is not
related to technological backwardness or something intimately related to
industrial production (as the technicist view would have it), but that
since it appear in the thought of Herbert Simon in his opposition to
industrial democracy, there is a relation between a concept of the role of
man in society, and the crafting of these technologies.



# The recurring interest in de Prony's project suggests a connection between
# thoughts on machine intelligence, automation, and sociotechnical systems
# for the conduct of workers, which contributes to a better understanding of
# the influence of ICTs on the future of work than the technicist view.

* 無 Would You Bet Against Sex Robots? 
** 待 Introduction
The dominant technicist view, which analyses the perils of ICTs for the
future of work in terms of the possibilities to automate different
(categories of) tasks, is inadequate because it ignores the conventionalist
dimension of the wage relation by construing work from a realist
epistemology.

** 待 The Technicist View 
*** 待 Introduction (What is the Technicist View?)
# As Autor's article shows, the technicist view analyses the perils of ICTs
# for the future of work in terms of the possibilities to automate different
# tasks at a low cost.

For the purposes of this thesis, the ``technicist'' view, is defined as the
application of a realist epistemology to the question of the influence of
automation on work. This view posits that work is a historical universal---
work is, allegedly, common to all human societies---that automation
facilitates. Therefore, this view understands the question from the angle
of the technical possibilities to mechanize a task. Moreover, in this view,
jobs are understood as simply collections of tasks. The argument goes,
then, that if all the tasks in a job can be mechanized, automation would
erase this job if the mechanization is cost-efficient for a firm. I contend
that many mainstream economists and many computer scientists that discuss
the problem of automation on the future of work, be they pessimist or
optimistic of the prospects of ICTs, hold either this view or one that
resembles it. Since MIT economist David Autor is one of the respected
mainstream economists that has studied the longest the question of the
consequences of automation, his paper citetitle:autor2015 will be analyzed
as an ideal type of the way mainstream economists tackle this question. His
is a thoughtful exposition of a mildly optimistic pessimistic on the
question, which will be analyzed in detail for the purpose of seeing the
technicist view in action.

# The technicist view comes in the pessimist variety and the optimist
# variety. The optimists believe that AI, given its great promises, will
# change many different jobs, which will produce mass unemployment.
*** What is Autor's Take

#+ATTR_LATEX: :options [{\cite[5]{autor2015}}]
#+BEGIN_displayquote
In this essay, I begin by identifying the reason that automation has not
wiped out a majority of jobs over the decades and centuries. Automation
does indeed substitute for labor---as it is typically intended to do.
However, automation also complements labor, raises output in ways that lead
to higher demand for labor, and interacts with adjustments in labor supply.
Indeed, a key observation of the paper is that journalists and even expert
commentators tend to overstate the extent of machine substitution for human
labor and ignore the strong complementarities between automation and labor
that increase productivity, raise earnings, and augment demand for labor.

Changes in technology do alter the types of jobs available and what those
jobs pay. In the last few decades, one noticeable change has been
“polarization” of the labor market, in which wage gains went
disproportionately to those at the top and at the bottom of the income and
skill distribution, not to those in the middle. I will offer some evidence
on this phenomenon. However, I will also argue that this polarization is
unlikely to continue very far into the foreseeable future.
#+END_displayquote


Autor begins his article by mentioning the usual introductory economics
textbook example of the Luddites.

Autor asks, ``Why doesn't automation /necessarily/ reduce aggregate
employment, even as it demonstrably reduces labor requirements per unit of
output produced?''. Here, it is necessary to remember that Autor, as is
customary within neoclassical economics, sees employment as depending on
productivity and the ``demand'' of the labor market. His question reflects
an understanding of employment as determined by this two factors. Hence,
his perplexity could be framed as: If automation reduces the necessity to
employ workers at certain tasks, why is it that we do not see a reduction
of aggregate employment? 

Autor begins by pointing out that in 1900, 41 percent of the US workforce
was employed in agriculture; by 2000 that share had fallen to 2 percent
(Autor 2014), mostly due to a wide range of technologies including
automated machinery. 


#+ATTR_LATEX: :options [{\cite[26]{autor2015}}]
#+BEGIN_displayquote
A final point, typically neglected in recent dismal prophesies of
machine-human substitution, is that if human labor is indeed rendered
superfluous by automation, then our chief economic problem will be one of
distribution, not of scarcity. \ldots Here, I recall the observations of
economist, computer scientist, and Nobel laureate Herbert Simon (1966), who
wrote at the time of the automation anxiety of the 1960s: ``Insofar as they
are economic problems at all, the world’s problems in this generation and
the next are problems of scarcity, not of intolerable abundance. The
bogeyman of automation consumes worrying capacity that should be saved for
real problems \ldots'' A half century on, I believe the evidence favors
Simon's view.
#+END_displayquote

# His position could thus be caricatured as that of the mocked book of
# Kenneth Rogoff, ``nothing will change, but everything will change''.

*** Role of automatic machinery 
#+ATTR_LATEX: :options [{\cite[5]{autor2015}}]
#+BEGIN_displayquote
Whether the technology is tractors, assembly lines, or spreadsheets, the
first-order goal is to substitute mechanical power for human musculature,
machine consistency for human handiwork, and digital calculation for slow
and error-prone ``wetware.''
#+END_displayquote

He concedes that most workplace technologies are designed to save labor. 

# #+ATTR_LATEX: :options {2019/04/24}
# #+BEGIN_note
# Here Autor's argument has a slight historical problem: the first 
# machine calculators were actually very error-prone, thus, the association
# of machinery with error-free execution as calculation is concerned is
# relatively recent, probably only going as far back as Victorian England.
# #+END_note
*** The Two Sets of Tasks 

#+ATTR_LATEX: :options [{\cite[9]{autor2015}}]
#+BEGIN_displayquote
\ldots we distinguish two broad sets of tasks that have proven stubbornly
challenging to computerize. One category includes tasks that require
problem-solving capabilities, intuition, creativity, and persuasion. These
tasks, which we term “abstract,” are characteristic of professional,
technical, and managerial occupations. They employ workers with high levels
of education and analytical capability, and they place a premium on
inductive reasoning, communications ability, and expert mastery. The second
broad category includes tasks requiring situational adaptability, visual
and language recognition, and in-person interactions—which we call
``manual'' tasks. Manual tasks are characteristic of food preparation and
serving jobs, cleaning and janitorial work, grounds cleaning and
maintenance, in-person health assistance by home health aides, and numerous
jobs in security and protective services.
#+END_displayquote


#+ATTR_LATEX: :options [{\cite[18]{autor2015}}]
#+BEGIN_displayquote
Stated plainly, the growth of occupational employment across skill levels
looks U-shaped earlier in the period, with gains at low-skill and
high-skill levels. By the 2000s, the pattern of occupational employment
across skill levels began to resemble a downward ramp. In Autor (2015), I
present a more detailed breakdown of these patterns, and in particular
suggest that the set of abstract task-intensive jobs is not growing as
rapidly as the potential supply of highly educated workers.
#+END_displayquote


Finally, here Autor discusses the international dimension of the changes in
the US labor market. He mentions, among other things, the rise of China as
a premier manufacturing exporter, and its consequences on US workers,
reducing employment in directly import-competing US manufacturing
industries and depressing labor demand in manufacturing and
non-manufacturing sectors that served as upstream suppliers to these
industries (i.e., their subsidiaries). 

#+ATTR_LATEX: :options [{\cite[18]{autor2015}}]
#+BEGIN_displayquote
Of course, these forces are in various ways linked with the spread of
automation and technology. Advances in information and communications
technologies have changed job demands in US workplaces directly and also
indirectly, by making it increasingly feasible and cost-effective for firms
to source, monitor, and coordinate complex production processes at
disparate locations worldwide and altering competitive conditions for US
manufacturers and workers. This multidimensional complementarity among
causal factors makes it both conceptually and empirically difficult to
isolate the ``pure'' effect of any one factor.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[18]{autor2015}}]
#+BEGIN_displayquote
This essay has emphasized that jobs are made up of many tasks and that
while automation and computerization can substitute for some of them,
understanding the interaction between technology and employment requires
thinking about more than just substitution. It requires thinking about the
range of tasks involved in jobs, and how human labor can often complement
new technology. It also requires thinking about price and income
elasticities for different kinds of output, and about labor supply
responses.
#+END_displayquote

*** 無 Complementarities 

#+ATTR_LATEX: :options [{\cite[5]{autor2015}}]
#+BEGIN_displayquote
I argue that the interplay between machine and human comparative advantage
allows computers to substitute for workers in performing routine,
codifiable tasks while amplifying the comparative advantage of workers in
supplying problem-solving skills, adaptability, and creativity. \ldots In
many cases, machines both substitute for and complement human
labor. Focusing only on what is lost misses a central economic mechanism by
which automation affects the demand for labor: raising the value of the
tasks that workers uniquely supply.
#+END_displayquote

This makes sense in the economists world picture that although certainly
very much changed, still retains a flavor  of a mechanical systems of
different forces balancing each other in equilibrium: when one thing
changes, this change is balanced by adjustments in the systems that
mitigate this change. 

# Indeed, a key observation of the paper is that journalists and even expert
# commentators tend to overstate the extent of machine substitution for human
# labor and ignore the strong complementarities between automation and labor
# that increase productivity, raise earnings, and augment demand for labor.

*** Polarization of the job Market
Changes in technology do alter the types of jobs available and what those
jobs pay. In the last few decades, one noticeable change has been
“polarization” of the labor market, in which wage gains went
disproportionately to those at the top and at the bottom of the income and
skill distribution, not to those in the middle. I will offer some evidence
on this phenomenon. However, I will also argue that this polarization is
unlikely to continue very far into the foreseeable future.

Autor claims that the elasticity of labor supply can mitigate wage gains.
Namely, a flow of new workers can temper any wage gains that would emanate
from complementarities between automation and human labor input. 

#+ATTR_LATEX: :options [{\cite[7]{autor2015}}]
#+BEGIN_displayquote
Even if automation does not reduce the quantity of jobs, it may greatly
affect the qualities of jobs available. 
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[9]{autor2015}}]
#+BEGIN_displayquote
But the scope for this kind of substitution is bounded because there are
many tasks that people understand tacitly and accomplish effortlessly but
for which neither computer programmers nor anyone else can enunciate the
explicit “rules” or procedures. I have referred to this constraint as
Polanyi’s paradox, named after the economist, philosopher, and chemist who
observed in 1966, “We know more than we can tell” (Polanyi 1966; Autor
2015).
#+END_displayquote


Autor then discusses the phenomenon of ``job polarization'' (Goos and
Manning, 2003) in which the simultaneous growth of high-education,
high-wage jobs at one end and low-education, low-wage jobs at the other end
occurs at the expense of middle-wage, middle education jobs. Autor believes
this is the case since, following his characterization of tasks between
/abstract/ and /manual/, both are found at opposite ends of the skill
spectrum---in professional, managerial, and technical occupations on the
one hand, and in service and laborer occupations on the other. 

Labor supply to manual task-intensive occupations is intrinsically elastic, due 
to their generally low education and training requirements. This insight does not 
preclude the possibility that wages in manual tasks will rise, at least to some extent. As 
Baumol (1967) observed, even absent productivity growth in technologically lagging 
occupations, wages in these occupations must rise over time with societal income to 
compensate workers for not entering other sectors (again, assuming that demand 
for these activities is relatively inelastic). But it does suggest that wage increases in 
these jobs will be restrained to some extent by the labor supply response, including 
from workers displaced in other sectors of the economy.

This citation summarizes Autor's thoughts on the effects of automation on
manual task-intensive activities. Briefly, he believes that they are weakly
complemented by computerization, difficult to outsource, and face and
elastic labor supply that reduces their likelihood of wage increases due to
increased demand. Autor claims that in a 2013 paper with Dorn, he presents
evidence that wages for manual-tasks occupations rose during the 1990s when
labor markets in the United States were extremely tight, but after 2000
wages fell with the expansion of manual task-intensive service occupations.

*** 待 Conclusion

However, the limit of these studies is that they interpret the challenge of
automation by artificial intelligence as simply that of estimating with a
macroeconomic model the impacts of the substitution of capital for labor in
employment rates, wages, etc. My position is that this way of framing and
analysing the problem is not very interesting and offers very little
insight on the wider issue of the changes portended by artificial
intelligence.

My point of view is that many of the various analysis on this matter are
marred by their narrow scope that only focuses on the possible impact of
new technologies on what economists call macroeconomic varibales. Briefly
put, the views of neoclassical or mainstream economists, whether optimists
or pessimists are decided on whatever the economist thinks that the impact
of these technologies will be on macroeconomic variables such as
investment, consumption, employments, wages, etc.
*** 取 Example of Bank Tellers
Autor then describes an example with bank tellers documented by Bessen
(2015). According to him, ATMs were introduced in the 1970s, and their
numbers in the US economy quadrupled from approximately 100,000 to 400,000
between 1995 and 2010. But these machines did not eliminate bank tellers:
their employment rose from 500,000 to approximately 550,000 over the
30-year period from 1980 to 2010 (although given the growth in the labor
force in this time interval, these numbers do imply that bank tellers
declined as a share of overall US employment).

#+ATTR_LATEX: :options [{\cite[6]{autor2015}}]
#+BEGIN_displayquote
ATMs indirectly increased the demand for tellers: the number of tellers /per
branch/ fell by more than a third between 1899 and 2004, but the number or
urban bank branches (also encouraged by a wave of bank deregulation
allowing more branches) rose by more than 40 percent. 
#+END_displayquote

This example of his is actually quite weak. After all, an increase of only
50,000, taking into account demographic growth over the same period, is
negligible. 
** 中 The Historicity of the Wage Relation 
# The second part of chapter one criticizes the technicist view by showing
# that it ignores the conventionalist dimension of the concept of work, which
# for the purposes of the kind of work discussed by Autor et al., is the
# historical and cultural specificity of the wage relation. To show this
# historical and cultural specificity of the work concept, I will refer to
# the example of work in Mesopotamia (in the context of the bi-metallic
# monetary system), and the work contract in French Law as discussed by Alain
# Supiot. [In case of running out of time, just go for Supiot, which might be
# the easiest to read in a short amount of time]
*** 阻 Introduction 
*** 取 Balancing System
One of the shortcomings of the paper, which is not specific to it but to
economists, is the social ontology that undergirds it. Economists---whether
critical or favorable to the social system of production, exchange, and
distribution---tend to presuppose the existence of an order more or less
strictly determined by laws and tendencies.

# as for the liberal economists, they would like to point to its stability
# and the perils of human intervention to derange it.
# But, the technicist view is inadequate because ?

# for by focusing on the identification of general trends of the past
# advances in automation, it has a inadequate ahistorical understanding of
# history, for by believing that what was true then is also true today, it
# fails to identify the great ruptures and changes in our understanding of
# work. 


When Autor claims that ``Focusing only on what is lost misses a central
economic mechanism by which automation affects the demand for labor'', one
can notice immediately the belief in economic laws in and economic orderly
system that somehow operate to compensate the disequilibrium caused by
automation. My point is that this belief in an economic order, economic
laws, system-wide logic, or whatever term the author favors, prevents an
understanding of social change. Whatever the method of analysis used, a
surreptitious belief in the /harmonies economiques/ (or otherwise, what have
been called /invisible hand/ explanations) prevents the comprehension of
social change, for any change is construed as being countered or
compensated by a social /force/, which guarantees that the immanent stability
of the system, its /economy/, remains in balance. 

This /invisible hand/ element is present in Autor's paper when he support his
claim for the mitigated effects of worker redundancy thanks to automation
``raising the value of the tasks that workers uniquely supply''. The reason
this is the case is that he assumes that there are tasks that workers
uniquely supply, and thus, those who can perform such tasks will not only
be still employed, but will see their earnings increased due to /economic
laws/. 


Note here, that even though, many an economist would feel embarrassed to
use the term /economic law/, the fact that it is avoided does not detract
from the fact that it still encapsulates the belief of economists on an
economic order (whether in equilibrium as in neoclassical economics, or in
constant contradiction and movement as in Marxism) that regulates social
processes.

Here, the author's position is clear. He believes that automation brings
new complementarities into play in the job market, and thus, that mitigates
the unemployment caused by worker redundancy. 


In this example one notices the contradictions of the analysis of the
organization of work from the perspective of political economy. Political
economy is not just a rationalization of social organization carved out of
theology. Rather political economy has in its core the belief in natural
principles of organization (laws) of systems. Whether one thinks of this
laws as tending towards welfare (as economic Liberalism) or catastrophe (as
in Marxist political economy), one has to question the possibility of an
analysis of the organization of work from this perspective: that is to say,
the perspective of a kind of order, regulating principle, or homeostatic
mechanisms. Whether one talks of economics as a more scientific descendant
of political economy, does not respond to the implications of this thinking
in terms of laws or immanent orders. Is it possible to reconcile this
perspective with our call for a conventionalist epistemology? My short
answer is no.

*** 待 Historical Universals
The problem with Autor's interpretation of what a job is, is that he
basically thinks that a job is just a collection of tasks, so he is
essentially leaving out the important part of the fact that a job is
defined in Law and that it entails certain rights and responsibilities. 

The article in the edited volume on Labor in the Ancient World by ??
poses the important question that is usually left out of today's writings
on the so-called labor market: It is very hard to get people to work for
one's account. The explication of why anybody would to choose to work for
others is usually "explained" by the division of labor and the mutually
advantageous exchange, but the question is left out of why would anyone
choose to do this, instead of provide it from the household economy. 

As an example of this shortcoming, see how Autor claims that ``the
elasticity of labor supply can mitigate wage gains''. But here we must
wonder, why is it that there is any labor supply. This might seem a moot
point or avoiding the question. But in fact, most contemporary analyzes of
the ``labor market'' tend to assume the very difficult problem of how to
get people to work for a wage. As studies of ancient Mesopotamia have
shown, the problem for these ancient /economies/ was not /unemployment/ but
lack of population to be employed (mostly by the palace and temples) to do
all the tasks required. And, this was due to a social and institutional
configuration in which most of the people, then peasants, were not
alienated from their means of subsistence (specifically arable land), and
thus, they kept not only a certain independence vis-à-vis public
authorities, but also vis-à-vis other possible /employers/.  


Nonetheless, another reason to employ humans is the fact that there /are/
people to be employed. This might seem trivial, since economists, who like
Autor, are in the business of producing models, tend to abstract from the
social conditions of possibility. But this, I believe is a crucial thing to
take into account in the evolution of work and employment. As studies of
ancient Mesopotamia have shown, the problem for these /economies/ was not
/unemployment/ but lack of population to be employed (mostly by the palace
and temples) to do all the tasks. And, this was due to a social and
institutional configuration in which most of the people, then peasants,
were not alienated from their means of subsistence (specifically arable
land), and thus, they kept not only a certain independence vis-à-vis public
authorities, but also vis-à-vis other possible /employers/. That is to say,
the vast majority of people, the peasantry, had very little need or
incentive to work for others, when they could just work for themselves.
This fact, is passes inadvertently in contemporary literature on the
``labor market,'' which ignores that it is very hard to convince people to
willingly work for one's own account. 


The reason to bring this example up, is that the employment relation (or
what French sociology of work has more accurately called the /salariat/)
depends on certain social and institutional conditions that analyzes such
as Autor's assume will not change with the development of the ICTs.

One must explain the social conditions that make a majority of the
population be willing to sell their labor in exchanges for wages, what in
the french sociology of work (/sociologie du travail/) is called /le salariat/
(i.e.,, the institution of wage earning). The /salariat/ passes inadvertently
in economic analysis of the job market, but I claim that one must
understand the changes brought by automation not in terms of the relation
of technology to concrete tasks, but rather in relation to the social
conditions of salariat.


We must acknowledge that exchange is culturally situated, and that
understanding the economic activity of exchange as a transhistoric
phenomenon is a mistake. 


As Alain Supiot has argued, the work contract, at least in the case of
French Civil Law, has a history and its related to slavery.

However, here we see one of the problems of the realist epistemology
mentioned previously. After all, the job market is taken as a realistic
entity, and its conventionalist character is not recognized. 

How technical changes affect employment will also depend on the conventions
for employment and its legal regulations. As textcite:schaffer1994 points
out, this conventions are not a side show, but a necessary prerequisite for
technical change.


# He is wrong to think that the problem is one of scarcity. Scarcity is
# socially constructed. The biggest problem for our societies is one of
# distribution. And, here, automation could actually makes things worse, for
# as Autor rightly points out, more automation is likely going to shift
# around jobs, instead eliminating completely everyone (though certainly
# some) out of employment. As he points out, ``In simple economic models,
# this outcome cannot really occur because capital is owned by the economic
# agents who are presumably also the workers; but, alternatively, the returns
# could accrue to a narrow subset of agents.'' So clearly the question with
# automation is more likely to be, who will benefit from it? Will the gains
# in productivity be enjoined only by a minority of capital owners, who reap
# profits, and the propertied classes that can afford these benefits, while
# vast swats of blue-collar workers are reduced to house servants? 


[The importance of the alienation of people from the means of subsistence,
long ago noted by Marx (189X), is important even for the narrow aim of
estimating the macroeconomic impact of automation in the labor market. The
fact that workers in most of today's cities require a job to pay for the
necessities of life, means that, unlike, say a semi-peasant household,
today's workers will demand high wages, since they whole depend on them for
their subsistence.] 

# mention  the legal changes of the new tehcnologies. 

*** 待 My Propositions
My claim is that his analyzes has two important shortcomings: First, the
question that interests or worries computer scientists is not simply the
effects of ICTs on the /rate/ of unemployment. This question, which has been
treated extensively, in my humble opinion, is not very interesting. I think
that what computer scientists wonder about are the changes that these
technologies will bring on work, and the employment relation. One measure
of this, is the current historical meeting point between crypto-currencies
and anarchist politics. The potential that crypto-anarchists see, for
example, in these technologies is the organization of economic activity
that escapes subordination to the state, and thus guarantees more
individual freedom. 

My position in this thesis is that, just as textcite:schaffer1994 did for
the analysis of automation in Victorian Great Britain, we should analyze
the changes of automation not just as a question of changes in employment
but as a question of changes of labor, the nature of work, and the nature
of the social organization of production. 


The visibilization of the automatic machines  of the factory rendered
invisible the workers whose lives and bodies were reorganized around it.


What is at stake here, I argue, is not whether machines will replace humans
in every single task. Rather, the question that automation raises is that
of the place of the human in the production and reproduction of society. 

Notice that nowhere in the document does he discuss the worsening of
working conditions due to technology. Notice how he mention ``restaurant
meals, cleaning services, haircare, and personal fitness'' as sectors
where since demand for them appears strongly income-elastic, rising
productivity in technologically leading sectors may boost employment in
these activities. 

We need not worry, we can all work providing services for the rich. That's
the good life.



Autor simply leaves aside the wider issues of the limit between nature and
artifice, between man and machine.

Just to clarify, I am not advocating a technological deterministic view of
history here, but I am simply pointing out that these blue sky dreams of
the promises of artificial intelligence are not simply connected to simple
changes in automated tasks, but to the social and political possibilities
opened up by these technologies. That is to say, although it is naive to
believe that society will be turned upside down by artificial intelligence,
it is equally naive to believe that social conditions of production will
remain unchanged. Just to name one example, the fact that important numbers
of today's researchers on artificial intelligence are housed in private
companies with a certain independence from government objectives also
brings questions about the transformation of society brought on by the
accumulation of power and the legitimacy to govern by those tech
corporations, such as Google, Facebook, etc. As an honorable tradition in
history of management theory has it, the exercise a authority within a firm
has to be understood within the context of the political sovereignty
exercised by the state. To think them separately, as is the case with
certain strands of American political culture, subordination of workers to
corporations and the consequences this has for the conduct of life and the
loss of individual freedom is missed. One great change that goes unnoticed,
due to the indue emphasis on the accumulation of financial resources by
Silicon Valley, is the fact that these corporations are not just paying but
also organizing the research on ICTs. If the shifting of power in the
corporation out of corporate boards to other concerned parties such as
workers, consumers, citizens, etc. For as textcite:mirowski2011 claims,
there has been a very big change in the social organization of American
science since the end of the second world war, passing from a state-led to
a private firms-led model of funding and organization of science. And, if
there is one area where this is most obvious is in artificial intelligence,
where big tech giants such as Google and Facebook are responsible for
directing some of the most important research projects in this domain.


If artificial intelligence brings about any meaningful changes, my point of
view is, this will not depend on the particular tasks that it helps
automate, such as the discussion is today with self-driving cars, but
rather on the changes in the social conditions of production that these
changes might bring.

*** 取 Arbitrary Division of Tasks
Although Autor does include problem-solving as one of the components of
what he terms ``abstract'' tasks, and although he even cites Herbert Simon,
who, along with Allen Newell, was one of the great proponents of the
importance of problem-solving in social systems, he does not seem to have
taken in Simon's message. For Simon, problem-solving was a sort of
meta-category to describe all processes of a subsystem (a person, a firm, a
mechanical component, etc.) to adapt to a larger system (i.e., its
environment). In fact, the latter Simon even attempted to simulate
something as rarefied as scientific expert problem-solving. As Sent claims,
``Like managers in political and administrative organizations, agents in
economic systems and problem-solvers in cognitive psychology, scientists
are boundedly rational in dividing goals into subgoals, employing
heuristics and satisficing. Furthermore, the scientists themselves are
complex, hierarchical systems.'' autocite:sent2001.

Notice that by dividing tasks between ``abstract'' and ``manual'', Autor
distinguishes between those that require problem-solving, intuition,
creativity, and persuasion on the one hand, and those that require
situational adaptability, visual and language recognition, and in-person
interactions. His distinction is not at all clear. 


In addition to Autor's framing the question as just a matter of estimating
the impact of automation on the rate of unemployment, his second
shortcoming is to try to estimate the impact on the rate of employment (and
wages) by analyzing the problem of automation in relation to the technical
character of the tasks being automated. My claim is that the question of
the technical changes brought by automation should be analyzed instead in
relation to the changes to the social conditions of the employment
relation, and not in relation to the particular, technical character of the
tasks being automated. 


Notice how here, Autor turns upside down the discourse of Babbage, for
Autor believes that it is abstract and not manual tasks that can be most
easily automated. Although Autor's claims do not constitute a valorization
of manual tasks, he does seem to believe that /those/ are the jobs most
difficult to be replaced by machines.

Autor's division of tasks is misleading in explaining the lack of
introduction of automation for certain jobs. One of the reasons for not
replacing, say hotel check-in staff, is not necessarily that automating
their tasks presents a technical difficulty; in other words, the continual
usage of humans for this job has nothing to little to  do with the nature
of the task in question. 

On the one hand, one reason is economical: such robots do not exist yet,
and thus, it remains cheaper for a business to employ humans. And, yes
humans for this particular task are still more flexible than robots, in the
sense that most artificial intelligence today is task-specific.





Essentially Autor's analysis rests on the claim that the correct way to
analyze the changes brought by automation on employment is better
understood through the relation between the technical possibilities of
automation and the technical character of the concrete tasks that make part
of jobs. 



*** 取 The Social-embeddedness of Work 
The article in the edited volume on Labor in the Ancient World by ??
poses the important question that is usually left out of today's writings
on the so-called labor market: It is very hard to get people to work for
one's account. The explication of why anybody would to choose to work for
others is usually "explained" by the division of labor and the mutually
advantageous exchange, but the question is left out of why would anyone
choose to do this, instead of provide it from the household economy. 

We must acknowledge that exchange is culturally situated, and that
understanding the economic activity of exchange as a transhistoric
phenomenon is a mistake. 


# It is very hard to have somebody work for you, so the wage relation is
# actually historical and it obeys to a particular organization of
# production.

# Use MMT and Michael Hudson to argue about work in ancient Mesopotamia. 

# One of the problems of the technicist view is that it takes for granted
# the existence of the institutional framework . However, thinking in terms
# of institutions is not necessarily useful, in this case, for there is
# already a tradition in economic history that emphasizes their existence,
# but this tradition has the problem that it argues usually in terms of the
# superiority of the dyad liberal democracy + capitalism. I think, thus, it
# may be better to think in terms of conventions, for this terms casts aside
# the Hayekian influence of institutional thinking that sees institutions as
# emerging. This is problematic precisely because this is an ahistorical
# doctrine, so actually it doesn't help to think of change properly speaking. 
 

*** 阻 Conclusion

For example, will the masses of unemployed drivers become part of
government job-guarantee programs cite:wray1998_2003 that will in turn put
more pressure on private sector businesses to improve working conditions?
Will the government instead opt to provide incentives to the private sector
to create replacements jobs while providing a basic income to those unable
to be profitable employed by private enterprise? Will this new class of
state dependents become a pariah class that threatens social cohesion? I
think these are the questions that artificial intelligence really brings to
the fore. 


** 阻 Conclusion
We need a different framework to study the influence of automation in the
future of work that takes into account the historicity of the work concept
and that leaves out the presupposition of social laws or social
regularities. This is not to deny that social regularities exits, but that
thinking in terms of regularities does not help to think about change. We
should, thus ask the question what is different, in terms of what has
changed. 
* 無 Did Adam Smith Invent the Digital Computer?
#+ATTR_LATEX: :options [Simon, 1973, The Next Hundred Years: Engineering Design]
#+BEGIN_displayquote
Nor was the intellectual significance of Babbage's computer understood
until the soul found its body a century later. In the absence of a
practical realization, the computer did not attract enough attention of
sharp minds to reveal its real significance. Even Babbage did not envision
his computer as equipotential with the human mind. He did not see that the
powers with which he had endowed it in order to enable it to make general
arithmetic calculations are the powers the human mind uses in order to
think and to understand language.
#+END_displayquote

# In the second chapter, I should sketch a different view (to the dominant
# technicist one) by explaining how the recurring interest in de Prony's
# project shows that thoughts on machine intelligence, automation, and
# sociotechnical systems for the conduct of workers have been connected since
# at least the nineteenth century.
** 待 Introduction 
#+ATTR_LATEX: :options [{\cite[2]{simon_newell1958}}]
#+BEGIN_displayquote
 As you will see, this story shows that physicists and electrical engineers
 had little to do with the invention of the digital computer---that the
 real inventor was the economist Adam Smith, whose idea was translated into
 hardware through successive stages of development by two mathematicians,
 Prony and Babbage.
#+END_displayquote

On November 14, 1957, in an address to the Twelfth National Meeting of the
Operations Research Society of America, Herbert Simon advanced the
provocative proposition that ``physicists and electrical engineers had
little to do with the invention of the digital computer'', for ``the real
inventor was the economist Adam Smith, whose idea was translated into
hardware through successive stage of development by two mathematicians,
Prony and Babbage.'' cite:simon_newell1958. 

:Unused:
# As the recurring interest in de Prony's project for the calculation of the
# logarithmic tables shows, the dominant "technicist" view of the influence
# of ICTs on the future of work and its organization is inadequate because it
# ignores that thoughts on machine intelligence, automation, and
# sociotechnical systems for the conduct of workers have been strongly
# connected since at least the nineteenth century.

# Why de Prony's project for the calculation of the logarithmic tables shows
# that early computing machines, the division of labor and the emergence of
# new sociotechnical systems of worker surveillance have been strongly
# connected.

# machine intelligence
# automation
# sociotechnical systems for the conduct of workers 

:END:

# The recurring interest in de Prony's project suggests a connection between
# thoughts on machine intelligence, automation, and sociotechnical systems
# for the conduct of workers, which contributes to a better understanding of
# the influence of ICTs on the future of work than the technicist view.
** 無 Manufacturing Logarithms and Weaving Algebraical Patterns 
# The first part of chapter two shows that the origins of the computer lie in
# a technical organization of labor that is related to the factory system and
# the concept of the division of (mental) labor. Therefore, in this part of
# tell of de Prony's project and I show how when Babbage looked at it, he saw
# in it the proof that mental labor could be mechanized, which had portentous
# influences for the history of intelligence and the history of economics. 
*** 待 Introduction
The division of labor as embodied in the allocation of tasks in de Prony's
project shows, the first large /computing/ project was not only a project
that showed the efficiency of the distribution of mental labor, but a new
form of subordination of the mind to a particular organization of mental
work in which workers were not only deprived of control but of full
knowledge over the productive process.

Remember to describe what de Prony's project was about
*** 無 The Division of Labor as the Foundational Concept of the Computer
**** 取 Who is Prony?
Gaspard Clair Francois Marie Riche de Prony (1755--1839) was born in
Cahmelet in the Beaujolais region of Southern France to a family of the
provincial middle bourgeoisie---the social class that would fill the ranks
of the Revolution and Empire's bureaucracy cite:picon_et_al1984. After an
education in the Classics, in 1776, when he was twenty-one, he entered the
École des ponts et chaussées in Paris. Prony's life coincides with a period
of the institutionalization of French sciences and techniques with the
foundation in 1794 of the École polytechnique---where he was appointed
professor of analysis and mechanics with Joseph-Louis Lagrange---and the
École normale supérieure, and a growing interest of the savants for applied
problems, and the generalization of the application of mathematical
formalisms.

# Following the educational reforms of the French Revolution, he was
# appointed professor of analysis and mechanics with Joseph-Louis Lagrange
# (1736--1813), at the newly founded Ecole Polytechnique from 1794. From 1798
# he was also made Director of the Ecole des Ponts et Chaussees, another post
# which he retained until the end of his life.

**** 無 Background on the Tables Project
En 1790, l’Assemblée nationale décida de remplacer les anciens impôts par
une contribution foncière assise sur le revenu net des propriétés (6). Elle
suivait en cela les idées de l’économiste François Quesnay. Créé en 1791,
le Bureau du Cadastre avec la mission précise de faire établir ces
cadastres parcellaires dans chacune des communes françaises.[fn:1] In
connection with this plan, it was decided that a very large set of
logarithmic and trigonometric tables would be prepared to supplement the
metric system (which had been inaugurated as nature's own measure, eternal
and immutable).

With the adoption of the decimal-based metric system, the Revolutionary
government rendered all older trigonometric tables computed using
traditional sexagesimal divisions of the circle suddenly unusable, at least
for French geodesists and astronomers bound to the new system. Although
originally commissioned as part of the Cadastre of France, launched in
1791, with Prony as director, the logarithmic tables having been expressly
designed for the decimal division of the angles of the quadrant, which,
along with the decimal division of time was later abandoned as part of the
metric system.

**** 無 Prony's Atelier
 Prony gave some details of the project in a 'Notice' read to the classe
des sciences mathematiques et physiques in 1801, soon after it was
finished. 

The personnel were divided into three sections according to the
work they did. 

At the apex, in the first section contained a handful of mathematicians,
including A. M. Legendre, C. A. Prieur de la Cote d'Or, and Lazare Carnot.
They chose the mathematical formulae to be used for calculation and
checking, and also considered the choice of initial values of the numbers
or angles, the number of decimal places to be adopted in each table, and so
on. Below them, in the second section comprised several `Calculators',
including the mathematicians A. M. Parseval (of the well-known formula in
infinite series) and the textbook writer J. G. Gamier, who determined the
values, and the differences of various orders, that needed to be
calculated. They also prepared a page of tables for the numerical work by
laying out the columns of the chosen values and the first row of entries,
and preparing the instructions on the preparation of the remaining entries
on the page. At the base, in the third section, these calculations were
done by the third section, a large team of between 60 and 80
assistants.[fn:2] Many of these workers were unemployed hairdressers; one
of the most hated symbols of the ancien regime had been the hair-styles of
the aristocracy, and the obligatory reduction of coiffure 'as the geometers
say, to its most simplest expression' left the hairdressing trade in a
severe state of recession.Thus these artists were converted into elementary
arithmeticians, executing only additions and subtractions.

knowing only the rudiments of arithmetic who would perform millions of
additions and subtractions and enter the values by hand into ruled folio
volumes specially laid out of the purpose. By means of these
``manufacturing'' methods, as Prony later called them, two copies of the
tables, each consisting of seventeen manuscript volumes plus instructions,
were completed by 1801.


# the calculation; below them seven or eight ``calculators'' [ /calculateurs/;
# sometimes also called /algébristes/ ] trained in analysis who would deduce
# form these formulas the numbers needed to begin actual computations; and at
# the base were seventy or eghty perons [ /individus/; also /ouvriers/ ] 

**** 無 Work and Calculation 
Si la démarche de Prony demeure isolee, dans un contexte de production
encore largement traditionnel, elle marque tout de même l'ouverture d'un
novueau front. L'organisation du travail devient raient une affaire
d’ingénieur, même si le cahntier ne suit pas le mouvement, et si
l'industrialisation se fait encore attendre. 

Les tables du Cadastre prennent une connotation tout aussi politique que
scientifique. Les méthodes employees pour venir à bout de cette tâche
gigantesque traduisent qant à elles des enejxy de rationalisation sociale.
Concrètement, cette divsion du travail se manifaste par une organisation
hiérarchique des compétences. 

Work and mechanical were closely linked in both French and English usage
until the middle decades of the nineteenth century, and the middle term
that joined them was the laboring body. Work taxed the body but not the
mind; even the most deft manipulations of ``rude mechanicals'' were
ascribed to habit and instinct rather than thought.

Calculation had not yet become mechanical, the paradigmatic example of
preocesses that were mental but not intelligent. Allied with the higher
mental faculties of speculative reason and moral judgment, calculation was
remote from the realm of menial labor, of the automatic and the habitual.

Astonishing feats of mental arithmetic were soon to beocme the province of
the idiot savant and the sideshow attraction, no longer the first augury of
profound mathematical gifts

Calculation took on the dull, patient associatoins of repetitive and
ill-paid bodily labor, ranked as the lowest of the mental faculties.

In so doing, it pushed calculation away from intelligence and towards work. 

# Prony did not read their symbolism as Charles Babbage.

# #+ATTR_LATEX: :options [{\cite[55]{friedmann1953}}]
# #+BEGIN_displayquote
# Il est intéressant de faire ici le rapprochement des définitions que donne
# l'Encyclopédie de l'« artisan » et de l'« artiste » (t. I, p. 745) : le
# premier est « le nom par lequel on désigne les ouvriers qui professent ceux
# d'entre les arts mécaniques qui supposent le moins d'intelligence. On dit
# d'un bon Cordonnier que c'est un bon artisan, et d'un habile Horloger que
# c'est un grand artiste ». Par « artiste », on entend les « ouvriers qui
# excellent dans ceux d'entre les arts mécaniques qui supposent
# l'intelligence ; et même à ceux qui, dans certaines Sciences, moitié
# pratiques, moitié spéculatives, en entendent très bien la partie pratique ;
# ainsi on dit d'un Chimiste qui fait exécuter adroitement les procédés que
# d'autres ont inventés, que c'est un bon artiste ; avec cette différence que
# le mot artiste est toujours un éloge dans le premier cas, et que, dans le
# second, c'est presque un reproche de ne posséder que la partie subalterne
# de sa profession ». — On voit que nous sommes encore fort loin des contenus
# et résonances actuels. 
# #+END_displayquote

*** 無 The Ghost in Babbage's Engines
**** Cogwheel Brain
They all form instantiations of Lord kelvin's dictum (Thomson [1884] 1987,
111, also 296) that we can only understand something if we can make a
mechanical model of it. Babbage's Difference Engines and the new formal
logic developed by Boole, De Morgan, and Jevons were driving forces in the
development of mechanical reasoning in all these senses. 

Halfway through the nineteenth century, the categorical distinction between
the phenomena of mind and matter vanished under the influence of
developments within psychophysiology. This enabled economists such as
Jevons to transgress the boundaries traditionally set to the tools of the
natural sciences might be used to disclose the laws of the mind.

**** Babbage Reads Prony

Babbage's calculating engines project emerged out of a growing need for
precise and accurate tables by the quickly industrializing British economy.
These tables were necessary, among other things, for navigation and for
insurance companies that were rapidly growing in importance. 

There were so many faults that could be made in the production of numerical
tables, in the computations of the ``avalanche of numbers'' comprised in
them, in the copying of the outcomes, and in the various stages of the
printing process that Herschel and Babbage spent many hours checking these
tables themselves for their own scientific purposes. One one such occasion,
as the story goes, Babbage exclaimed in exasperation that the wished these
computations had been made by ``steam'' (see for example, Swade 2000, 15).

Indeed, soon afterwards, in a pamphlet of 1822 on 'the application of
machinery to the purpose of calculating and printing mathematical
tables'---his main publication for securing governmental support for
production of the Difference Engine---he gave some account of de Prony's
project and noted that mechanical methods would speed up the process of
calculation. Clearly he was struck by de Prony's production of the tables
following an industrial process, and was hoping to imitate the process by
mechanical means. In his book on manufactures, he rehearsed some of the
same material on de Prony's project and on mechanical calculation.

#+ATTR_LATEX: :options [{\cite[223]{colebrooke1823}}]
#+BEGIN_displayquote
In other cases, mechanical devices have substituted machines for simpler
tools or for bodily labour. The artist has been furnished with command of
power beyond human strength, joined with precision surpassing any ordinary
attainment of dexterity. He is enabled to perform singly the work of a
multitude, with the accuracy of a select few, by mechanism which takes the
place of manual labour or assists its efforts. But the invention, to which
I am adverting, comes in place of mental exertion: it substitutes
mechanical performance for an intellectual process: and that performance is
effected with celerity and exactness unattainable in ordinary methods, even
by incessant practice and undiverted attention.
#+END_displayquote

 Prony's approach showed Babbage that it was possible to mechanize not only
 physical, but also mental, labor. His interest in the French project fits
 into his wider perception of algorithmic procedures in ``mathematics,
 science, and other walks of life'' (Grattan-Guinness 1992, 34). 

Babbage emphasized in /Machinery and Manufactures/ ([1835] 1963), still one
 of the most fascinating studies on the emerging mechanization of the
 economy, that the lowest task of Prony's project was ``almost'' a form of
 mechanized mental labor. Babbage designed his Difference Engine to
 mechanize this lowest stage of computing. Its method of computation
 ingeniously incorporated the method of differences in its wheels and
 gears, hence its name. Babbage's Difference Engine promised to fulfill all
 requirements Herschel and Babbage had been lamenting about: It saved
 calculation time and produced accurate and precise numbers. The
 computations would be more accurate than when done by a human
 individual---for machines, as opposed to humans, were thought not to make
 unpredictable mistakes. An attached printer would prevent errors in
 transcribing the outcomes. By thus excluding human interference from the
 whole process of computing and printing, all sources of faults---human
 faults---would be prevented, and the numbers would be precise, accurate,
 reliable, and reproducible. All this, of course, was based on the
 assumption that the machine itself operated flawlessly, a matter of great
 concern to Babbage. For all his calculating engines, he designed automatic
 checks and stops to secure its proper working.

Prony's approach affected the traditional view of the hierarchy of mental
and physical labor, Before Prony started his table project, computations
were, for the most part, made by mathematicians themselves for their own
purposes (Warwick 1995, 317--8). The routinisation and then mechanization
of computing downgraded calculation to the lowest of mental activities,
thus equating it with the routine labor executed in the emerging factories.

Babbage exploited the comparison of calculation with routine factory labor
in straightforwardly paralleling Prony's division of tasks with the
division of tasks necessary for the construction of a ``cotton or
silk-mill''. The ``multitude of other persons'' (the calculators or their
mechanical equivalent) used in their employment the ``lower degree of
skill'' (Hyman  1989, 143).

Babbage, writing of the project in 1832, was still obliged to admit that his
claim ``that the division of labor can be applied with equal success to
mental operations'' would ``appear paradoxical to some of our readers.''
The labor of mechanicals emptied the task of intelligence; yet the task at
issue, calculation, had been understood to be the very essence of
intelligence.

With Babbage's Difference Engine, thoughts on machine intelligence were
really only speculations, for it was obvious that the calculating
capacities of the machine still involved a considerable amount of separate
mental activity that was not captured in mechanical terms. The development
of an even more ambitious machine, the Analytical Engine, seemed to
overcome these limitations. The new contrivance derived its name from its
ability to perform all ordinary analysis.

In contrast to the Difference Engine, the Analytical Engine could be really
programmed. In fact, as is well-known, the design showed great similarity
with von Neumann's computer design a century later (see Swade 2000). The
comparison Babbage made with a silk mill, in /The Economy of Machinery and
manufactures/, should be taken literally; the Analytical Engine incorporates
in its design the architecture of a factory. The Analytical Engine combined
the calculation of various functions without the interference of human mind
and hand. This was attained by the use of punched cards, an idea that
Babbage got when he was working on his book. The idea originated from the
famous Jacquard loom, in which a complex mechanism of levers regulated the
lifting of the warp in accordance with the desired pattern. This was done
by triggering the right set of levers by a role of punched cards. These
cards activated a system of levers to lift the intended column of
gears. (Maas)
**** 無 Schaffer Engine and Technology of Social Control
Gesturing toward the urgent issues of technological redundancy and the
subordination of the labor process, Colebrooke's remark provides the theme
of my story of the connection which Babbage helped forge between the
development of machinofactures and the design of intelligent machines. In
early nineteenth-century Britain the word /intelligence/ simultaneously
embodied the growing system of social surveillance and the emerging
mechanization of natural philosophies of mind.

Babbage's Analytical Engine, a mechanical computer, was inspired by and
modeled on a new social organization of work: the large-scale division of
labor, as evidenced in the English machinetool industry and in the French
government's manufacturing of logarithmic and trigonometric tables for the
new decimal system in the 1790s. 

That said, we can interpret Lovelace's oft-repeated citation that "the
Analytical Engine /weaves algebraical patterns/ just as the Jacquard-loom
weaves flowers" (Lovelace, 25) in a more mundane form. Those who operated the
Jacquard-loom 

"In enabling mechanism to combine together /general/ symbols in successions
of unlimited variety and extent, a uniting link is established between the
operations of matter and the abstract mental processes of the most abstract
branch of mathematical science." (Lovelace, 25)

Babbage's severe blow to traditional categories of natural theology and
moral philosophy was only convincing, however, on the assumption that the
caprices of his calculating engines served as analogies to the world at
large, the natural and the moral, which is more or less a definition of
mechanical reasoning: to understand the world by means of machines. (Maas)

#+ATTR_LATEX: :options {2019/04/24}
#+BEGIN_note
This is key in the discourse on the upcoming changes of artificial
intelligence in the workplace. Automation renders invisible the labor, the
people who have to work to device these systems. 
#+END_note

#+ATTR_LATEX: :options [Lardner in the Edinburgh Review in {\cite[78]{babbage1889_2010}}]
#+BEGIN_displayquote
Another of the uses which the slightest attention to the details of this
notation irresistibly forces upon our notice, is to exhibit, in the form of
a connected plan or map, the organization of an extensive factory, or any
great public institution, in which a vast number of individuals are
employed, and their duties regulated (as they generally are or ought to be)
by a consistent and well-digested system. The mechanical notation is
admirably adapted, not only to express such an organized connection of
human agents, but even to suggest the improvements of which such
organization is susceptible—to betray its weak and defective points, and to
disclose, at a glance, the origin of any fault which may, from time to
time, be observed in the working of the system.
#+END_displayquote


The replacement of individual human intelligence by machine intelligence
was as apparent in the workshop as in the egnines. This task was both
/politically/ and /economically/ necessary.

#+ATTR_LATEX: :options [{\cite[39]{babbage1832_2009}}]
#+BEGIN_displayquote
One of the most singular advantages we derive from machinery is in the
check which it affords against the inattention, the idleness, or the
knavery, of human agents.
#+END_displayquote


What happened in the reogrganization of production in the system of
production of pulley blocks for the Royal Navy between 1795 and 1807 was
that machinery wasnt there just to make the process more productive.
Machinery was there to set the standard of what the ideal behavior of the
workforce should be: obedient, fast, coordinated, etc. Machines were not
replacements of workers as much as they were idealized version of the
working body. Machines were organized as an idealized workforce under the
gaze of the sociotechnical manager: Taylorism /avant la lettre/. Later, once
the application of machinery was thorough, and workers were required to
/adapt/ to new working conditions, they weren't passibily adapting to an
inocous technical change; they were conforming to idealized versions of
themselves.


#+ATTR_LATEX: :options [{\cite[214]{schaffer1994}}]
#+BEGIN_displayquote
\ldots economic rationality fought with traditional forms of exchange, or,
following Michel Foucault, with Benthamite strategies for the surveillance
of the body in the illuminated spaces of the Panopticon. Babbage's
campaigns for machine intelligence take their place alongside these more
familiar strategies for the reconfiguration of the productive body.
#+END_displayquote
*** 待 Conclusion
** 無 The Impossibility of a Democratic Computer
*** 待 Introduction
*** 無 Structural-functionalism and Ontological Monism
#+BEGIN_summary
Here I should discuss the problems of the 
#+END_summary 

#+ATTR_LATEX: :options [{\cite[294]{simon1951}}]
#+BEGIN_displayquote
We will say that $B$ exercises authority over $W$ if $W$ permits $B$ to select
$x$. That is, $W$ accepts authority when his behavior is determined by $B$'s
decision. In general, $W$ will accept authority only if $x_0$, the $x$ chosen by
$B$, is restricted to some given subset ($W$'s ``area of acceptance'') of all the
possible values. This is the definition of authority that is most generally
employed in modern administrative theory.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[295]{simon1951}}]
#+BEGIN_displayquote
$W$ will be willing to enter an employment contract with $B$ only if it
does not matter to him ``very much'' which $x$ (within the agreed upon area
of acceptance) $B$ will choose or if $W$ is compensated in some way for the
possibility that $B$ will choose an $x$ that is not desired by $W$ (i.e.,
that $B$ will ask $W$ to perform an unpleasant task).
#+END_displayquote

Many social scientists viewed the world as a complex, hierarchic system in
which science models the processes and relations that define such
systems. Moreover, a ``broad church'' positivism fostered an enthusiasm for
behavioral-function social science. 

The study of decisions-making offered the possibility to reform society
through the construction of rational systems, undeterred by the
irrationality of the individuals. After all, a decision could be shown to
be rational, even if the decider was not. Choices could be rational within
the appropriate framework. 

#+ATTR_LATEX: :options [{\cite[1-2]{ashby1953}}]
#+BEGIN_displayquote
\ldots for I have long been of the opinion that the problem of how ten
billion nerve cells work harmoniously together in the brain is the same
problem of how two billion people can work harmoniously together in a
society.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[39]{simon1983b}}]
#+BEGIN_displayquote
Even though we place supreme importance on having democratic control (that
is employee control) of political institutions, it does not follow as a
matter of logic that we want similar democratic control of the authority in
business organizations---as contrasted with controls through markets,
through bargaining, and through governmental regulations, or some
combination of these. It does not follow as a matter of logic that, simply
because voting is the primary mechanism of control at the societal level,
it has to be the primary mechanism of control of the level of individual
institutions within the society.
#+END_displayquote


#+ATTR_LATEX: :options [{\cite[6]{simon1954a}}]
#+BEGIN_displayquote
Functional analysis consists, then, in a correlation between the processes
and mechanisms that are operable in a system and the totality of conditions
that is sufficient for the maintenance of the invariance of the relations
that define the system. At the grossest level of analysis, we analyze
``survival'' into its component relations; at finer stages of analysis, we
analyze these components into systems of mechanisms, and into the elements
of these systems.
#+END_displayquote

In Simon's picture of homo administrativus man is nothing by himself, but
only in relation to an organization. 

To Simon, organizations were vast decision-making machines specialized
vertically into hierarchies in order to coordinate the successive
elaboration of decision premises down to the level where specific action
can be taken. For Simon, the constraints which organizations posed upon
rationality were not ``iron cages'' of bureaucratic domination, but rather
what made rationality possible.



*** 無 Bounded Rationality Summons Hierarchy 

#+BEGIN_summary
Here I discuss the political implications of the concept of bounded
rationality, for I contend that 

I discuss the anti-democratic consequences of Simon's notion of bounded
rationality. The claim is that although Simon himself wasn't personally in
favor of authoritarian government, there important anti-democratic
implications in terms of workplace democracy 

Since the New Deal, thinking of workplace democracy has given place to
discussion on living standards with the understanding that people give up
their claim on control over the work process in exchange for rising living
standards. Today with the floundering of the wage relation (/salariat/), the
new proletarian has  
#+END_summary 

Instead of /homo œconomicus/, Simon's model of man was /homo adaptivus/: the
adaptive, problem-solving organism of finite powers that moved in an
infinitely complex hierarchically organized environment. 

#+ATTR_LATEX: :options [{\cite[1-2]{ashby1953}}]
#+BEGIN_displayquote
``Design'' offers a solution of how it is done the brain, of how the
system, started at any random state, can /automatically/ improve its ways of
working, improving in ways that are far beyond the comprehension of the
units that compose it. It ought, therefore, to be possible, by using the
same principle to get a society organised so that it too starts
/automatically/ to improve its ways of behaving, improving them by
reactions that are too clever to be understood by the people that compose it.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[92]{simon1945_1997}}]
#+BEGIN_displayquote
It is impossible for the behavior of a single, isolated individual to reach
nay high degree of rationality. the number of alternatives he must explore
is so great, the information he would need to evaluate them so vast that
even an approximation is hard to conceive. Individual choice takes place in
a n environment of ``givens''---premises that are accepted by the subject
as bases for his choice; and behavior is adaptive only within the limits st
by these ``givens.''
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[195]{daston1994}}]
#+BEGIN_displayquote
Prony himself remarked upon the social oddity represented by ``the quite
singular gathering of men who had had such different existences in the
world'' and upon the intellectual anomaly that the fewest computational
errors were made by those ``who had the most limited intelligence, an
automatic existence, so to speak''.
#+END_displayquote

#+ATTR_LATEX: :options {french}[{\cite[53]{prony1804}}]
#+BEGIN_foreigndisplayquote
\ldots ils ont ete communement au nombre d'environ soixante ou
quatre-vingts; les neuf dixiemes au moins d'entre eux savoient tout au plus
les deux ou les quatre premieres regles de l'arithmetique, et ceux qui en
savoient davantage n'ont pas toujours ete les moins sujets a erreur.
#+END_foreigndisplayquote


Calculation had up to that point been an intellectual occupation fit for
the fines minds and the best society. 


#+ATTR_LATEX: :options [Simon cited in {\cite[46]{simon1945_1997}}]
#+BEGIN_displayquote
The rational individual is, and must be, an organized and institutionalized individual.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[117]{simon1945_1997}}]
#+BEGIN_displayquote
Human rationality operates, then, within the limits of a psychological
environment. This environment imposes on the individual as "givens" a
selection of factors upon which he must base his decisions.
#+END_displayquote


At this point in my research, I can at most suggest a connection, but given
Simon's thinking in organizations, it would be useful to read together his
technical work on computing in the light of his work on organizations (as
has been suggested by Heyck 2005).

#+ATTR_LATEX: :options [{\cite[92]{simon1945_1997}}]
#+BEGIN_displayquote
One function that organization performs is to place the organization members
in a psychological environment that will adapt their decisions to the
organization objectives, and will provide them with the information needed
to make these decisions correctly.
#+END_displayquote

#+ATTR_LATEX: :options [{\cite[36]{simon1983b}}]
#+BEGIN_displayquote
We have authority in organizations, based on the employment relation
between employee and employer, because it provides a very effective way of
organizing human efforts under conditions of uncertainty---under conditions
where coordinated action is needed, but where it is not known today in
detail what actions will be needed tomorrow. The employment relation
permits effective, coordinated action to be carried out by organizations
under such conditions of uncertainty. And the employment relation is the
primary source of authority in organizations in our society.
#+END_displayquote


However, here we should note something, one of the pioneers of artificial
intelligence cite:simon1983b, agreed with worker subordination, as he
argued that workers should submit to the organizational hierarchy. As Simon
defended his attack on industrial democracy: ``Employees who are informed
and consulted can usually be expected to work more effectively and with
more enthusiasm than those whoa re not, and to contribute important
elements of expertness out the decision-making process. I suppose that even
the conductor of the symphony orchestra asks the concertmaster for
suggestions during rehearsals---or if he does not, might improve the
orchestra's quality by doing so. But that is a very different matter from
organizing the orchestra as a voting body with the members holding formal
rights to participate I most of the management decisions''.

Simon continues: ``We must learn that democracy and politics are all part
of the same package of imperfect human institutions, constructed of
imperfect human beings. We want to have democratic institutions, and the
price we pay for them is to put up with the political process, There seems
to be no institutional design that gives us the benefits of the one without
the costs of the other.''

Simon's explanation of the necessity of authority within the employment
relation due to the existence of uncertainty is a dangerous naturalization
of hierarchy as simply a necessary consequence of the complexity of the
environment and our bounded rationality which makes us unable to fully
grasp it. 
*** 待 Conclusion
** 待 Conclusion

* 待 Conclusion
\printbibliography[title=References]

* Footnotes
[fn:2] My presentation of the Project draws from that of
textcite:grattan-guinness2003. textcite:roegel2011, who has closely studied
the lists of the employees at the Cadastre, disagrees with
Grattan-Guinness's emphasizing of the employment of hairdressers as
calculators because he suspects that `` there were only two or three of
them'' [[parencite:roegel2011][p. 26]]. Nonetheless, Roegel points out that
the first mention of the anecdote seems to be an \ordinalnum{11} November
1824 discourse by engineer Charles Dupin---Prony's close friend--- from
which Grattan-Guinness drew upon parencite:dupin1824.

[fn:1] Durant onze années, le Cadastre a réalisé deux sortes de travaux :
des cartes et des tables. Nous montrerons ci-après comment ces tâches se
sont substituées à l’objectif initial qui était de nature fiscale : établir
la répartition de la contribution foncière parencite:peaucelle2012a.
 
